### ISSUE TITLE
<comma-and-join> tag in templates for another language

### ISSUE THREAD

**Issue by cosad3s** [Syslifters/sysreptor#101]
In the HTML+Vue template, we can use the tag `<comma-and-join>`.
After rendering, the last comma is replaced by `and` by default (English).
How to edit this behaviour in order to have this word for another language (Ex: `<comma-and-join separator="et">` for French ?) ?
I cannot find documentation about this feature.

**Comment by MWedl** [comment]
Hi, there already exist parameters to adapt the text concatenation to use other separators. There is no documentation for it, though. We will add it to the design docs.

By default, `<comma-and-join>` concatenates text parts with commas and the last one with the english word "and".
These separators can be changed via the parameters `comma=", "` and `and=" and "` to format other languages.

This example joins text parts in different languages:
```html
English (default): <comma-and-join>...</comma-and-join>
English (no commas, always "and"): <comma-and-join comma=" and " and=" and ">...</comma-and-join>
German: <comma-and-join and=" und ">...</comma-and-join>
French: <comma-and-join and=" et ">...</comma-and-join>
```

**Comment by cosad3s** [comment]
That's perfect! Thank you :)
