### ISSUE TITLE
Ups. Something did not work while bringing up your containers.

### ISSUE THREAD

**Issue by Cristhianlord** [Syslifters/sysreptor#109]
![error_l](https://github.com/Syslifters/sysreptor/assets/69061410/fb7dcb2d-061d-472d-8399-17a07e2c21b2)
Hello, I followed the steps indicated but when I run your script I get the following error "Ups. Something didn't work when opening your containers.
".
Could you tell me what I should correct or what this message is due.

**Comment by aronmolnar** [comment]
Hello,
Can it be that you're using an outdated docker version? Can you post the version (`docker --version`)?

If so, can you update your Docker daemon?
You can then retry using the script (it will give you a command to delete your existing volumes. you can do this safely).

Or you continue manually by `cd` to `deploy` directory and...
```
docker compose -f docker-compose.yml up -d

username=reptor
docker compose exec app python3 manage.py createsuperuser --username "$username"

# Add demo data
# Projects
url="https://docs.sysreptor.com/assets/demo-projects.tar.gz"
curl -s "$url" | docker compose exec --no-TTY app python3 manage.py importdemodata --type=project --add-member="$username"

# Designs
url="https://docs.sysreptor.com/assets/demo-designs.tar.gz"
curl -s "$url" | docker compose exec --no-TTY app python3 manage.py importdemodata --type=design

# Finding templates
url="https://docs.sysreptor.com/assets/demo-templates.tar.gz"
curl -s "$url" | docker compose exec --no-TTY app python3 manage.py importdemodata --type=template
```

(For detailed description see: https://docs.sysreptor.com/setup/installation/#manual-installation)
