### ISSUE TITLE
Document sharing via SysReptor

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#122]
We currently allow rendered reports to be downloaded. They must be transmitted to the customer via a separate channel, like email.

This might not be the most comfortable and customer-friendly solution.

Additionally, pentesters might also want to share additional documents (like scan outputs, raw data, etc.).  
Customers might also want to share documents with pentesters (like PTA, credentials etc.).

It would be nice if SysReptor could additionally be used as a sharing platform.

Additional features could be...
• Sharing time recordings...
• Audit trail, when documents were downloaded and from which IP
• Expiration time
• Customers could delete files (or make  them inaccessible for) themselves to prevent further access
• Customer access could be reused in future projects
• IP restriction

See also https://github.com/Syslifters/sysreptor/discussions/9

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.74

SysReptor users can share notes by generating a publicy accessible link. The shared public link can have an expire date, optionally be password protected and be configured to provide readonly or read-write access.
