### ISSUE TITLE
String field validation via regex

### ISSUE THREAD

**Issue by MWedl** [Syslifters/sysreptor#127]
It is currently not possible to validate the content of string fields, all text inputs are accepted. It should be possible to configure a regex pattern for string fields in designs. This allows users to restrict string fields to specific formats (e.g. IP, email, URL, etc.). 

Implementation considerations:
* add an optional `pattern` field to the field definition of fields with `type=string`
* the field definition should be backward-compatible: i.e. do not fail when there is no `pattern` in the definition
* where to perform validation:
  * input fields in frontend: immediate user feedback
  * checks in project: generate a warning when regex validation fails
  * NOT when saving changes: the API should accept all string field text values. If the API returns a validation error, this would break auto-save.
* prevent regex denial of service via timeouts for regex validation

**Comment by aronmolnar** [comment]
We maybe want to provide default regex patterns for certain use cases, like a drop down where to choose email, URL, into, float, custom,...

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2023.142
