### ISSUE TITLE
Ambiguous naming of Design Snapshots

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#130]
When a design is updated multiple time during a day, and is applied to a project, there are multiple design snapshots with the same naming.

![image](https://github.com/Syslifters/sysreptor/assets/25219407/1792b1a3-49ee-466f-9bcb-9de738c3d18a)

Short-term solutions would be to add the time (e.g. "07:57"; at least if there is more than one snapshot with the same date), or add a counter.

A long-term solution might be to introduce versioning of designs, but this goes beyond the purpose of this ticket.

Additionally, we should improve the ordering of the drop-down:
* First the public designs (not snapshots)
* Then design snapshots ordered by creation time (from new to old)

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2023.142
