### ISSUE TITLE
Error while running docs.sysreptor.com/install.sh

### ISSUE THREAD

**Issue by puzzithinker** [Syslifters/sysreptor#137]
[ERROR] reportcreator_api.archive.import_export.import_export: Error while importing archive. Rolling back import.
Traceback (most recent call last):
  File "/app/api/reportcreator_api/archive/import_export/import_export.py", line 139, in import_archive
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'created': [ErrorDetail(string='This field is required.', code='required')], 'project_type': {'created': [ErrorDetail(string='This field is required.', code='required')], 'assets': [{'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}]}, 'sections': [{'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}], 'findings': [{'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}], 'images': [{'created': [ErrorDetail(string='This field is required.', code='required')]}]}
Traceback (most recent call last):
  File "/app/api/manage.py", line 22, in <module>
    main()
  File "/app/api/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/app/api/reportcreator_api/management/commands/importdemodata.py", line 46, in handle
    imported = import_func(f)
  File "/app/api/reportcreator_api/archive/import_export/import_export.py", line 186, in import_projects
    return import_archive(archive_file, serializer_class=PentestProjectExportImportSerializer)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/app/api/reportcreator_api/archive/import_export/import_export.py", line 154, in import_archive
    raise ex
  File "/app/api/reportcreator_api/archive/import_export/import_export.py", line 139, in import_archive
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'created': [ErrorDetail(string='This field is required.', code='required')], 'project_type': {'created': [ErrorDetail(string='This field is required.', code='required')], 'assets': [{'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}]}, 'sections': [{'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}], 'findings': [{'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}, {'created': [ErrorDetail(string='This field is required.', code='required')]}], 'images': [{'created': [ErrorDetail(string='This field is required.', code='required')]}]}

**Comment by aronmolnar** [comment]
Hi @puzzithinker, thank's for your report.

It seems like you already had a SysReptor image locally before.
Can you delete the `sysreptor-app` image (`docker rmi sysreptor-app`)?

Steps for cleaning everything would be:
```
cd sysreptor/deploy
docker compose stop  # stop containers
cd ../..
docker rm -f sysreptor-app sysreptor-db sysreptor-languagetool  # remove containers
docker volume rm -f sysreptor-app-data sysreptor-db-data  # remove volumes (deletes all data)
rm -rf sysreptor  # deletes source code and app.env (incl your encryption and license keys)
```

Install: `curl -s https://docs.sysreptor.com/install.sh | bash`

**Comment by puzzithinker** [comment]
It's resolved by reinstalling Ubuntu lol
thanks!
