### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by brunomcuesta** [Syslifters/sysreptor#140]
Hello!
I'm getting this error when installing Sysreptor with docker compose.

**Command**:

`docker compose -f docker-compose.yml up -d`

**Output**:

```
=> ERROR [app frontend 1/1] RUN npm run generate

------
 > [app frontend 1/1] RUN npm run generate:
1.449 
1.449 > reportcreator-frontend@1.0.0 generate
1.449 > nuxt generate
1.449 
1.727 Nuxt 3.7.4 with Nitro 2.6.3
6.599 ℹ Building client...
6.612 ℹ vite v4.4.11 building for production...
6.863 ℹ transforming...
74.37 ℹ ✓ 3551 modules transformed.
76.62 ℹ rendering chunks...
102.4 
102.4 <--- Last few GCs --->
102.4 
102.4 [16:0x7fe37cbea020]    99443 ms: Mark-sweep (reduce) 1928.4 (1986.6) -> 1927.9 (1987.4) MB, 1361.6 / 0.0 ms  (average mu = 0.225, current mu = 0.020) allocation failure; scavenge might not succeed
102.4 [16:0x7fe37cbea020]   100889 ms: Mark-sweep (reduce) 1928.1 (1987.4) -> 1928.1 (1987.6) MB, 1206.7 / 0.0 ms  (average mu = 0.197, current mu = 0.166) allocation failure; GC in old space requested
102.4 
102.4 
102.4 <--- JS stacktrace --->
102.4 
102.4 FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
103.9 npm ERR! path /app/frontend
103.9 npm ERR! command failed
104.0 npm ERR! signal SIGABRT
104.0 npm ERR! command sh -c nuxt generate
104.0 
104.0 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-11-10T14_16_06_357Z-debug-0.log
------
failed to solve: process "/bin/sh -c npm run generate" did not complete successfully: exit code: 1
```

Searching the internet recommends increasing the memory allocation for the Node. I included the configuration in docker-compose.yml, but it didn't work.

```
environment:
    NODE_OPTIONS: "--max-old-space-size=4096"
```

Does anyone know how to solve it?
Thanks!

**Comment by aronmolnar** [comment]
Hi, you're trying to compile the sources yourself.
We distribute the precompiled sources in our releases which simplifies installation.

If you follow the setup instructions at https://docs.sysreptor.com/setup/installation/ you should not run into this issue.

**Comment by brunomcuesta** [comment]
> Hi, you're trying to compile the sources yourself. We distribute the precompiled sources in our releases which simplifies installation.
> 
> If you follow the setup instructions at https://docs.sysreptor.com/setup/installation/ you should not run into this issue.

Solved! Docker is running on a VM, so it needs to increase the VM's memory for the installation to be successful.
Thanks!
