### ISSUE TITLE
Notification about updates

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#141]
Currently, self-hosted installations need to be not only updated manually, users also need to check manually if there are updates available.

We might want to introduce a workflow (probably in our GitLab CI pipeline) that creates update notifications in the SysReptor UI automatically to inform users that a new update is available.

**Comment by mlec1** [comment]
Just a random idea: 

It would be cool to have the docker images already built (hosted on Dockerhub, Github, self hosted registry,... ): that would allow a better integration with tools like [Renovate](https://docs.renovatebot.com/), [Watchtower](https://containrrr.dev/watchtower/), or maybe [Dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide) (never used so not sure).

Maybe there is a technical reason which requires a manual build, I didn't check, it is just an idea

**Comment by aronmolnar** [comment]
Thanks for this suggestion. We also have this on our roadmap, but we've had reservations regarding licensing so far.
We need to have to evaluate this in more detail.

**Comment by MWedl** [comment]
Implemented automatic update notifications in https://github.com/Syslifters/sysreptor/releases/tag/2024.55
