### ISSUE TITLE
Difficulties to name the "ID" of a "property" of an "object" (data type) when editing a "Report/Finding Field" - lost of focus

### ISSUE THREAD

**Issue by Mathoulilou** [Syslifters/sysreptor#143]
Hello, 

When I want to create/edit the ID name of a Property of a Field (either Report or Finding Field) with the "object" Data Type, I am losing the focus of my cursor. I can only edit one character by one that makes the ID name edition difficult.

It seems that each time I put a new character on the ID name, an algorithm is sorting the list of the object properties and do not keep the focus on the "ID" field. 

I use the "community" edition of Sysreptor. Yet, this issue is also on the online Playground (https://demo.sysre.pt). I use Firefox on a Debian machine, with the last version of sysreptor.

I thank you very much for your work and your help !

Best, Math

**Comment by aronmolnar** [comment]
Thank you, I can reproduce the error and we try to fix this with the next release.

**Comment by MWedl** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2023.142
