### ISSUE TITLE
Basic CSS property text-shadow doesn't work

### ISSUE THREAD

**Issue by T0my-commits** [Syslifters/sysreptor#144]
Invalid CSS in design "My Template"

Ignored `text-shadow: 1px 1px 2px #0096FF` at 154:5, unknown property.

**Comment by MWedl** [comment]
Hi,
`text-shadow` is not supported by weasyprint, our HTML+CSS to PDF renderer. They have an GitHub issue for this, but it's open since 2012, so I don't think it will be implement it soon.

**Comment by T0my-commits** [comment]
Hi MWedl,
Too bad. Thank you for your reply.
