### ISSUE TITLE
[Bug] Arrow Movement in findings

### ISSUE THREAD

**Issue by GrylledCheez** [Syslifters/sysreptor#145]
Pressing up or down in a findings textbox switches focus to the button menu or another findings area.

**Comment by MWedl** [comment]
Thanks for reporting, I could reproduce this behavior. This bug seems to only affect fields inside lists. On top-level fields, pressing arrow keys work as expected and move the cursor one line up/down.

**Comment by MWedl** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2023.145
