### ISSUE TITLE
[Feature Request] Screen Offset while editing

### ISSUE THREAD

**Issue by GrylledCheez** [Syslifters/sysreptor#147]
When editing a document, there should be an option to keep the cursor x number of lines above the bottom of the page as well as x number of lines below the top.  It could also have a "keep in center" option.

This would allow us to know what comes next/before where we're typing. As an added benefit, it will reduce eyestrain.

**Comment by aronmolnar** [comment]
It is obviously quite annoying when the arrows do not work in this exact case (https://github.com/Syslifters/sysreptor/issues/145). But as soon as they do (working on a fix already), the solution for this should rather be to use the arrow keys to see the text that was pushed outside the view.

We looked at how other tools tackle this:
* Word -> does not implement this
* Joplin -> neither
* GitHub -> neither
* Notion keeps one line in sight

Weighing up complexity/efforts against usability improvements, we decided to not implement this at the moment.
