### ISSUE TITLE
Broken count?

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#15]
Hi there,

![Opera-2023-05-11 at 20 04 02@2x](https://github.com/Syslifters/sysreptor/assets/3596242/7eb29e02-ea64-4a00-a871-2886b0d7ba98)

I found that the executive summary is section 1, but also the document control is too.

**Comment by MWedl** [comment]
Hi, the count is not actually broken. It's an error in the design :)

Both sections have the same ID. If you change one ID, the heading number is rendered correctly in the table of contents.
![Screenshot_20230511_141529](https://github.com/Syslifters/sysreptor/assets/29510012/c67a4dde-a637-41be-a7c2-5460e3357c92)

**Comment by vysecurity** [comment]
Got it!
