### ISSUE TITLE
[Feature Request] - New Role "Project Admin"

### ISSUE THREAD

**Issue by firefart** [Syslifters/sysreptor#150]
Currently only the `Superuser` role is able to see **all** projects. It would be nice to have a `Project Admin` role which includes people that can create and edit projects but don't need Superuser rights.

The current workaround is to add those lower priv people to the team inside the Project but that makes these people appear in the teams table in the design.

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.74

**Comment by firefart** [comment]
Awesome thanks!
