### ISSUE TITLE
[Feature Request] Option to change the colour palette of the severity for a finding.

### ISSUE THREAD

**Issue by danperezasensio** [Syslifters/sysreptor#153]
It would be convenient to be able to change the colour palette for each type of finding based on its severity: info, low, medium, high, critical. This would allow to use custom color codes for specific needs.

**Comment by aronmolnar** [comment]
You can quite easily change the colors based on their severity in the CSS of your reports:

![CSS colors](https://github.com/Syslifters/sysreptor/assets/25219407/8f692299-5fcc-4061-a5b5-fab820df630e)

![Severity Overview](https://github.com/Syslifters/sysreptor/assets/25219407/d9a9b3e1-8dc5-46b8-9b47-1f1d2e114737)


In the reporting view in the SysReptor application, we also use colors based on severity. They are based on the finding field `CVSS` or `severity` (take precedence, if both exist).

![image](https://github.com/Syslifters/sysreptor/assets/25219407/7e5d6e77-b961-479e-866c-928b4a9beb8f)

Those colors are, however, not customizable at the moment.

Can you explain your exact need?

**Comment by silent6trinity** [comment]
Wouldn't this be the whole idea behind Risk impact / Risk likelihood?

**Comment by aronmolnar** [comment]
We currently do not plan to make those colors customizable.
