### ISSUE TITLE
[BUG] switching split-view and render jumps the page 

### ISSUE THREAD

**Issue by GrylledCheez** [Syslifters/sysreptor#156]
Steps to reproduce:
1. Create a finding
2. Add lots of steps to that finding
3. Add images to each of those ateps
4. Switch to render mode
5. Scroll down to somewhere in the middle of the steps
6. click the render mode again to go to normal view
7. Notice that the web page isn't where you'd expect it to be

Desired behavior:
1. The page should keep your current step in focus

I suggest that an onclick method should note which render button I press, the scroll so that is at the top or center of the page after the images are collapsed.

**Comment by MWedl** [comment]
Good suggestion. We will update the scroll position such that the button is at the same screen position.

**Comment by GrylledCheez** [comment]
Fixed in 8d59a98
