### ISSUE TITLE
Cannot upload svg files

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#16]
I deleted the background.svg file, then tried to upload it back onto the server. It gives me:

![Opera-2023-05-11 at 20 31 59@2x](https://github.com/Syslifters/sysreptor/assets/3596242/a63ed538-20c9-4e77-b132-8d020f3553ae)

**Comment by MWedl** [comment]
Works on my machine™

We do not restrict upload file sizes in Django. I was not able to reproduce this error (locally and on demo.sysre.pt). Is your instance behind a reverse proxy which limits file uploads?

**Comment by vysecurity** [comment]
Confirmed fix works.
