### ISSUE TITLE
[ DOCS ] - Finding Import

### ISSUE THREAD

**Issue by well-it-wasnt-me** [Syslifters/sysreptor#167]
Hi there !

Sorry, but i cant find anywhere any reference about the format to use in order to import findings

**Comment by aronmolnar** [comment]
Hi,
Where do you want to import findings?  
You can create findings in your report by clicking "Create finding" and you can use finding templates to add predefined texts.

If you want to import finding via CLI, you can use our CLI tool reptor.

```
cat finding.json | reptor finding
```

```title=finding.json
{
  "status": "in-progress",
  "data": {
    "cvss": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:L/I:L/A:N",
    "title": "Reflected XSS",
    "summary": "We detected a reflected XSS vulnerability.",
    "references": [
      "https://owasp.org/www-community/attacks/xss/"
    ],
    "description": "The impact was heavy.",
    "recommendation": "HTML encode user-supplied inputs.",
    "affected_components": [
      "https://example.com/alert(1)",
      "https://example.com/q=alert(1)"
    ]
  }
}
```
https://docs.sysreptor.com/cli/uploads/finding/

**Comment by well-it-wasnt-me** [comment]
thank you
