### ISSUE TITLE
[ ENHANCEMENT ] - ZeusCloud Import

### ISSUE THREAD

**Issue by well-it-wasnt-me** [Syslifters/sysreptor#168]
ZeusCloud is an amazing tool for checking misconfiguration and more in your AWS account. Beside being a bit stale is still working very good. It has, for now, the exporting of a json with all his finding. Would be nice to be able to import that into SysReptor

**Comment by aronmolnar** [comment]
You can bring the ZeusCloud output into a JSON format and use our CLI tool to create a finding in SysReptor.

```
cat finding.json | reptor finding
```
```
{
  "status": "in-progress",
  "data": {
    "cvss": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:L/I:L/A:N",
    "title": "Reflected XSS",
    "summary": "We detected a reflected XSS vulnerability.",
    "references": [
      "https://owasp.org/www-community/attacks/xss/"
    ],
    "description": "The impact was heavy.",
    "recommendation": "HTML encode user-supplied inputs.",
    "affected_components": [
      "https://example.com/alert(1)",
      "https://example.com/q=alert(1)"
    ]
  }
}
```

**Comment by well-it-wasnt-me** [comment]
will do ! while im at it im gonna build a python script to achieve that so you can integrate it into sysreptor (if you want)
