### ISSUE TITLE
Fallback to Severity value if CVSS is undefined

### ISSUE THREAD

**Issue by MWedl** [Syslifters/sysreptor#173]
### Discussed in https://github.com/Syslifters/sysreptor/discussions/172

<div type='discussions-op-text'>

<sup>Originally posted by **saintbarber** December 23, 2023</sup>
I would like to propose a small change on the Templates page.

Personally, I do not add CVSS scores to my finding templates, and prefer to specify the Severity field (I set it as a requirement), only if my clients request a CVSS score I add it.

That being said, when I create a finding template, without specifying the CVSS score, and specifying only the Severity (e.g. Criticlal) the finding shows up as Info on main Templates page:

 
![no-cvss-only-severity](https://github.com/Syslifters/sysreptor/assets/80729812/74e5db81-255d-4cd2-80b9-2b83fb2d1e7b)

![image](https://github.com/Syslifters/sysreptor/assets/80729812/b45d9f47-5b71-4063-8934-62d6f77abcb4)

Could we create some sort of fallback, if the CVSS score is undefined within the finding template, to use the Severity value and show only the levelName along with the corresponding colour? e.g.:

![image](https://github.com/Syslifters/sysreptor/assets/80729812/e0411db8-debd-4828-a937-3edb834ab1ab)

If neither the CVSS score, or the Severity is defined within the template, then the default `Info 0.0` will be shown.

I tried to implement this myself, but I have absolutely no idea how vue works (I envy those who understand) and unfortunately do not have the time to learn. 

Do you guys agree with this? Or is it something you do not plan to add?

Thank you again for the this tool btw, amazing work to everyone involved <3
</div>

**Comment by carter-falconops** [comment]
+1 to this - specifically when we use sysreptor to generate standard vulnerability scan reports via Nessus scans as not all findings are using the latest cvss calculator.

**Comment by aronmolnar** [comment]
Will be deployed with the upcoming release next week.

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.1
