### ISSUE TITLE
Logo field

### ISSUE THREAD

**Issue by mkannan22** [Syslifters/sysreptor#174]
Is there a field to upload logo into report and have it set to default or do I have to upload the logo and then manually change path in html editor?

**Comment by MWedl** [comment]
Hi, currently file fields are not implemented. 

If you only have a small set of logos (e.g. your company and 3 partner logos), you can upload all logos as assets in the design and create an enum field to choose the logo to use. This allows for defining a default logo (default enum value) and a convenient dropdown selection in reports. 

![image](https://github.com/Syslifters/sysreptor/assets/29510012/5f27ad1b-4c96-455e-8512-b0e441806457)

The enum value is available during report rendering as variable that can be used in vue template rendering.

```html
<img :src="`/assets/name/${report.logo.value}.png`" alt="logo" />
```

**Comment by mkannan22** [comment]
Thanks!!
