### ISSUE TITLE
UI crashed when pdfviewer on design page

### ISSUE THREAD

**Issue by kmahyyg** [Syslifters/sysreptor#176]
Browser Info:

Google Chrome | 120.0.6099.129 (Official Build) (arm64)
-- | --
Revision | `204016af461e03117aa3858b51ba4534c7cfda81-refs/branch-heads/6099_110@{#3}`
OS | macOS Version 13.6 (Build 22G120)
JavaScript | V8 12.0.267.10
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --disable-quic --use-angle=metal --enable-features=ChromeRefresh2023,ChromeWebuiRefresh2023,EncryptedClientHello,PdfOcr,UseDnsHttpsSvcbAlpn,WebRtcHideLocalIpsWithMdns --flag-switches-end --origin-trial-disabled-features=WebGPU

Screen resolution: 4k 

SysReptor version: Community 2023.145 (latest currently)

Screenshot:

![20231230-185150-Google Chrome-007083@2x](https://github.com/Syslifters/sysreptor/assets/16604643/54bad6e7-783e-482a-9304-18f880ea9c2b)

What I did:
- Open the demo template (HTB CPTS Reporting)
- Wait for a few seconds on PDF Designer tab (Now PDF viewer won't show anything)
- It crashed.

Expected:
- Works as intended.

Backend Logs:
```
[2023-12-30 10:49:07 +0000] [22] [INFO] Starting gunicorn 21.2.0
[2023-12-30 10:49:07 +0000] [22] [INFO] Listening at: http://0.0.0.0:8000 (22)
[2023-12-30 10:49:07 +0000] [22] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-12-30 10:49:07 +0000] [23] [INFO] Booting worker with pid: 23
[2023-12-30 10:49:07 +0000] [24] [INFO] Booting worker with pid: 24
[2023-12-30 10:49:07 +0000] [25] [INFO] Booting worker with pid: 25
[2023-12-30 10:49:07 +0000] [26] [INFO] Booting worker with pid: 26
2023-12-30 10:50:37,166 [INFO] reportcreator_api.tasks.querysets: Starting periodic task "cleanup_history"
2023-12-30 10:50:37,176 [INFO] reportcreator_api.tasks.querysets: Completed periodic task "cleanup_history" with status "success"
2023-12-30 10:54:08,055 [INFO] root: GET / 200 (user=REDACTED)
/usr/local/lib/python3.10/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
  warnings.warn(
/usr/local/lib/python3.10/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
  warnings.warn(
/usr/local/lib/python3.10/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
  warnings.warn(
2023-12-30 10:54:08,248 [INFO] root: GET /api/v1/pentestusers/self/ 200 (user=REDACTED)
2023-12-30 10:54:08,269 [INFO] root: GET /api/v1/utils/settings/ 200 (user=<none>)
2023-12-30 10:54:08,398 [INFO] root: GET /api/v1/pentestusers/self/notifications/ 200 (user=REDACTED)
2023-12-30 10:54:08,446 [INFO] root: GET /api/v1/pentestprojects/?readonly=false 200 (user=REDACTED)
2023-12-30 10:54:10,418 [INFO] root: GET /api/v1/findingtemplates/ 200 (user=REDACTED)
2023-12-30 10:54:11,955 [INFO] root: GET /api/v1/projecttypes/?scope=global&ordering=name 200 (user=REDACTED)
/usr/local/lib/python3.10/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
  warnings.warn(
2023-12-30 10:54:16,025 [INFO] root: GET /api/v1/projecttypes/8b40c46f-e829-4ff1-9db3-b3f6b375d7d2/ 200 (user=REDACTED)
2023-12-30 10:54:16,070 [INFO] root: POST /api/v1/projecttypes/8b40c46f-e829-4ff1-9db3-b3f6b375d7d2/lock/ 201 (user=REDACTED)
2023-12-30 10:54:17,881 [INFO] root: Function render_to_html took 0:00:01.724498
2023-12-30 10:54:18,829 [INFO] root: Function render_to_pdf took 0:00:00.947950
2023-12-30 10:54:18,829 [INFO] root: Function encrypt_pdf took 0:00:00.000002
2023-12-30 10:54:18,829 [INFO] root: Function render_pdf_task took 0:00:02.672885
2023-12-30 10:54:18,834 [INFO] root: POST /api/v1/projecttypes/8b40c46f-e829-4ff1-9db3-b3f6b375d7d2/preview/ 200 (user=REDACTED)
2023-12-30 10:54:46,220 [INFO] root: POST /api/v1/projecttypes/8b40c46f-e829-4ff1-9db3-b3f6b375d7d2/lock/ 200 (user=REDACTED)
2023-12-30 10:54:58,955 [INFO] root: POST /api/v1/projecttypes/8b40c46f-e829-4ff1-9db3-b3f6b375d7d2/lock/ 200 (user=REDACTED)
2023-12-30 10:55:00,703 [INFO] root: Function render_to_html took 0:00:01.725512
2023-12-30 10:55:01,631 [INFO] root: Function render_to_pdf took 0:00:00.926958
2023-12-30 10:55:01,631 [INFO] root: Function encrypt_pdf took 0:00:00.000002
2023-12-30 10:55:01,631 [INFO] root: Function render_pdf_task took 0:00:02.653093
2023-12-30 10:55:01,636 [INFO] root: POST /api/v1/projecttypes/8b40c46f-e829-4ff1-9db3-b3f6b375d7d2/preview/ 200 (user=REDACTED)
```

Configuration (app.env):
```
SECRET_KEY="64Bytes-base64-REDACTED,86 bytes string"
ENCRYPTION_KEYS='[{"id": "UUIDv4-here-REDACTED", "key": "32bytes-base64-redacted, 44 bytes string", "cipher": "AES-GCM", "revoked": false}]'
DEFAULT_ENCRYPTION_KEY_ID="UUIDv4-here-REDACTED"
MFA_FIDO2_RP_ID="MY-DOMAIN.com"
DEBUG=off
GUEST_USERS_CAN_CREATE_PROJECTS=False
GUEST_USERS_CAN_IMPORT_PROJECTS=False
GUEST_USERS_CAN_UPDATE_PROJECT_SETTINGS=False
GUEST_USERS_CAN_DELETE_PROJECTS=False
```

**Comment by kmahyyg** [comment]
Each page contains PDF viewer will crash.

**Comment by aronmolnar** [comment]
Thank you!
We are aware of this bug, and suspect it to be in the arm64 version of the Chrome browser. All other browsers do not seem to be affected.

**Comment by kmahyyg** [comment]
> Thank you! We are aware of this bug, and suspect it to be in the arm64 version of the Chrome browser. All other browsers do not seem to be affected.

On Windows (AMD64), this bug can sometimes be reproduced when editing "design" template, and preview will not work on this page.

However, on Windows (AMD64), when on "project" page, PDF renderer is working correctly.

Just for your reference, thanks for your help.

**Comment by aronmolnar** [comment]
Did you use Windows on a virtual machine on a Mac or on a dedicated hardware?

**Comment by kmahyyg** [comment]
My Windows is on another Dell laptop with Intel processor. But this bug cannot be stable reproduced on Windows (AMD64), and when "ah, snap" is triggered, the console of dev-tools showed nothing, usually pdf.js will print something and will show field lock logging when working correct.

And I could confirm this bug might related to Chrome ARM64 only (since I don't have Windows ARM64 device, so I couldn't confirm about Windows ARM64). On MacOS with M1 chip, with latest Firefox ESR, it's working correctly. 

I personally assume, this might be a deep hole in chromium codebase.

**Comment by aronmolnar** [comment]
Yeah, I also think so.

**Comment by kmahyyg** [comment]
> Yeah, I also think so.

I just narrowed it down a little bit:

By using ARM64 Windows 11 on my M1 Mac via VMWare Fusion:

- Edge 120 (ARM64) : working
- Chromium 120 (third-party binaries, ARM64) : Working

On M1 Mac, MacOS:
- Google Chrome: Crashed
- Chromium 117 (un-googled): Working
- FireFox: Working


So personally, I may suggest introduce a change in document about instruct users with Apple Silicon PC to use Chromium/Firefox instead of fixing this bug.

Thanks, I will close this issue since this bug should be out of your product scope.

Feel free to add more information if you'd like to.

**Comment by aronmolnar** [comment]
We got reports that some Windows users are also affected.

Some indications that we collected:
* Only Chrome, but not Edge or Chromium (or other Chromium-based browsers) seem to be affected
* There are indications that the Bitwarden browser extension could cause the crashes
* The bug is not perfectly reproducible, but most often affects the design page

**Comment by kmahyyg** [comment]
> There are indications that the Bitwarden browser extension could cause the crashes

Yes, I use bitwarden browser extension.

**Comment by Patralos** [comment]
> > There are indications that the Bitwarden browser extension could cause the crashes
> 
> Yes, I use bitwarden browser extension.

Could you please retry it with the bitwarden extension temporary disabled?

**Comment by kmahyyg** [comment]
> > > There are indications that the Bitwarden browser extension could cause the crashes
> > 
> > 
> > Yes, I use bitwarden browser extension.
> 
> Could you please retry it with the bitwarden extension temporary disabled?

I just tried it with Bitwarden disabled. The design page works smoothly with multiple built-in offsec and htb reporting design template, on M1 Mac, with current version of Google Chrome (120.0.6099.199)

Well, this message is totally a disaster to Bitwarden user like me. Passkey, TOTP, Password stuffs are all in it.

**Comment by Patralos** [comment]
> > > > There are indications that the Bitwarden browser extension could cause the crashes
> > > 
> > > 
> > > Yes, I use bitwarden browser extension.
> > 
> > 
> > Could you please retry it with the bitwarden extension temporary disabled?
> 
> I just tried it with Bitwarden disabled. The design page works smoothly with multiple built-in offsec and htb reporting design template, on M1 Mac, with current version of Google Chrome (120.0.6099.199)
> 
> Well, this message is totally a disaster to Bitwarden user like me. Passkey, TOTP, Password stuffs are all in it.


Don't worry, we also use Bitwarden here and we'll try to solve the problem. The more accurately we can isolate the source of the error, the better.

**Comment by Patralos** [comment]
> > > > There are indications that the Bitwarden browser extension could cause the crashes
> > > 
> > > 
> > > Yes, I use bitwarden browser extension.
> > 
> > 
> > Could you please retry it with the bitwarden extension temporary disabled?
> 
> I just tried it with Bitwarden disabled. The design page works smoothly with multiple built-in offsec and htb reporting design template, on M1 Mac, with current version of Google Chrome (120.0.6099.199)
> 
> Well, this message is totally a disaster to Bitwarden user like me. Passkey, TOTP, Password stuffs are all in it.

Can you please tell us how much RAM your Macbook has? We are able to reproduce the issue on two 16GB models, but not on a 32GB model.

**Comment by kmahyyg** [comment]
> > > > > There are indications that the Bitwarden browser extension could cause the crashes
> > > > 
> > > > 
> > > > Yes, I use bitwarden browser extension.
> > > 
> > > 
> > > Could you please retry it with the bitwarden extension temporary disabled?
> > 
> > 
> > I just tried it with Bitwarden disabled. The design page works smoothly with multiple built-in offsec and htb reporting design template, on M1 Mac, with current version of Google Chrome (120.0.6099.199)
> > Well, this message is totally a disaster to Bitwarden user like me. Passkey, TOTP, Password stuffs are all in it.
> 
> Can you please tell us how much RAM your Macbook has? We are able to reproduce the issue on two 16GB models, but not on a 32GB model.

16GB. However free RAM is enough. Memory pressure is lower than  50% and unused memory (excl. Cache & Compressed, according to activity monitor) is about 3GB.

**Comment by Patralos** [comment]
> 
> 16GB. However free RAM is enough. Memory pressure is lower than 50% and unused memory (excl. Cache & Compressed, according to activity monitor) is about 3GB.


It seems like we found a solution, which works on our machines 🙃, this fix is only on the dev branch at the moment. 

Would you be so kind and try to see if the problem is fixed for you in our dev demo?

The following link will give you a one time user and log you in automatically:
[https://cloud.sysreptor.com/demotest](https://cloud.sysreptor.com/demotest)

**Comment by kmahyyg** [comment]
> Would you be so kind and try to see if the problem is fixed for you in our dev demo?

It's working here, I tested 4 templates builtin in the dev test demo instance hosted on your cloud. No crash happened.

Approach: open each template in "design" and waiting until PDF has been rendered, skim all PDF pages.

Thanks.

**Comment by MWedl** [comment]
Released fix in https://github.com/Syslifters/sysreptor/releases/tag/2024.3
