### ISSUE TITLE
[feat req] binary artifact storage management

### ISSUE THREAD

**Issue by kmahyyg** [Syslifters/sysreptor#178]
When in "notes", allow attachment to be uploaded to local storage.

This is useful when collecting artifact uploaded / scan result in binary.

You may cooperate this with a newly self-hosted object storage like minio.

**Comment by aronmolnar** [comment]
You can copy/paste binary files to notes already.

If you want to use s3 instead of docker volumes of the host, you can configure it (minio compatible).
https://docs.sysreptor.com/setup/configuration/#s3-storage

**Comment by kmahyyg** [comment]
Wow, I just didn't think of drag-n-drop method. Thanks a lot.
Additional request: how can I delete files on local disk which is mistakenly uploaded to the site?

**Comment by MWedl** [comment]
Unreferenced files are cleaned up automatically by a periodic background task if they are no longer referenced. This means when all links to that file are deleted from markdown text, the file will soon after be deleted automatically.

For SysReptor professional, file references might end up in the version history and prevent automatic deletion. Once a project gets archived all currently unreferenced files are deleted (also from version history) and not included in the archive.
