### ISSUE TITLE
Report Filename

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#18]
Hi there,

Is there anyway to get the report file name such as:

```
{{report.filename}}
```

So it replaces content inside during generation?

**Comment by vysecurity** [comment]
I'm also wondering if there's any way to template:

{{report.customer}}

And if there is spaces:

{{report.customer | replaceSpacesWithUnderscores}}

... but I cannot use <script> in my HTML?

**Comment by MWedl** [comment]
Hi,

The filename is not available in the PDF rendering engine. The filename is applied to the finished PDF file while downloading. 

I don't know what your exact use case is, but I guess you want to display the filename in the report header or footer. You could add a custom report field for the filename in your design and render its content to the PDF header/footer. Or if you could generate a dynamic filename with variables in it (e.g. "report_{customer}_{title}.pdf"). In the publish page you can copy the filename from the PDF preview and paste it in the filename field, such that you don't have to type it every time.

To answer the second question:
The [Vue template language](https://vuejs.org/guide/essentials/template-syntax.html) allows JavaScript expressions inside the curly braces. You can use following expression to replace spaces with underscores.
```vue
{{ report.customer.replaceAll(' ', '_') }}
```

**Comment by vysecurity** [comment]
Thanks, that's fantastic. I'll give that a shot.

**Comment by vysecurity** [comment]
Works great.
