### ISSUE TITLE
CWE finding field

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#188]
There is a requirement for a CWE field type (that can be used as finding field).

It would be better to implement it as a dedicated field type (instead of an enum with many values) due to the large number of enum fields, which would all have to be loaded when a finding is opened.  
It could have a similar appearance as CVSS with an overlay for search functionality.

![image](https://github.com/Syslifters/sysreptor/assets/25219407/1f0b854e-cc32-4edb-9382-6441f03ea97d)

It could be a simple text search functionality. Maybe, filters would make sense (but here I need input from people who use CWE regularly).  
![image](https://github.com/Syslifters/sysreptor/assets/25219407/01d8d33b-7f26-46ff-bc94-3a63fb796503)

We could also return a data structure (as variable in Vue) to have additional data available in the report (like descriptions, links, programming languages, etc.).

To people who would find this feature useful:

* What filtering options do you need?
* What data do you need in the report?
* Should it be single-select or multi select?
* What else should we take into account?

**Comment by kmahyyg** [comment]
> What filtering options do you need?

maybe a quick search, for example: input "improper access" , then show "improper access control" CWE for selection in list.

> What data do you need in the report?

How about inserting a URL in report, like "CWE-200" for `[CWE-200](https://cwe.mitre.org/data/definitions/200.html)` in report.

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.13

**Comment by besplash** [comment]
@MWedl Any way of accessing the parent of the parent? Currently, the object only has the parent id, but no reference to the parent object.

**Comment by MWedl** [comment]
@besplash Currently not. SysReptor passes a CWE object (defined in https://github.com/Syslifters/sysreptor/blob/main/api/src/sysreptor/utils/fielddefinition/cwe.json) to the PDF rendering job without much post-processing. 

We could resolve the parent add add it as a `parent_cwe` object (and also recursively the parent's parent). However, the CWE data is a tree. Do you only need the parent or other data such as child or sibling CWEs as well? Could you please describe your use case?

**Comment by besplash** [comment]
@MWedl Parents are sufficient. 

Our customers want a higher level list of what type of vulnerabilities were assessed and which are vulnerable/not vulnerable. We currently use OWASP top 10s where possible and use custom lists otherwise. Unfortunately, these lists can become fairly big right now and become increasingly more complicated with workaround methods to mark each category properly. If we could just use some CWE pillars and use them as our groups instead, we could quickly check for each finding's CWE field, what parent it belongs to. For deeper nested CWEs, we need to be able to get the parent's parent.

**Comment by MWedl** [comment]
@besplash I have created a new issue for providing CWE parent data in PDF rendering. Let's continue the discussion there: #463
