### ISSUE TITLE
Blue Color References 

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#19]
For some reason I'm getting blue color in Matrix theme:

```
 <template v-if="finding.references && finding.references.length > 0">
            <h4>References:</h4>
            <ul id="ul-references">
              <template v-for="reference in finding.references">
                <li><a :href="reference">{{ reference }}</a></li>
              </template>
            </ul>
          </template>
```

I modified this a bit, but the ul-references ID is not being applied to the field. The links show up like:

![Opera-2023-05-12 at 12 55 45@2x](https://github.com/Syslifters/sysreptor/assets/3596242/98659422-b5f0-48d2-b3b8-c7487d5bcf0d)

**Comment by MWedl** [comment]
In the CSS of the Matrix design exists a helper class `link-none` which formats links links like regular text. You can add this class to `<a>` tags.
```html
<li><a :href="reference" class="link-none">{{ reference }}</a></li>
```

**Comment by vysecurity** [comment]
I managed to fix it!
