### ISSUE TITLE
Increase Contrast of Nested Elements

### ISSUE THREAD

**Issue by StephanPillhofer** [Syslifters/sysreptor#190]
Nested elements sometimes become hard to differantiate from each other while editing.

For example a list of objects which in term include objects.

A quick suggestion:
Add some simple background color variations to more easily see which properties belong to which element.

For example:
![grafik](https://github.com/Syslifters/sysreptor/assets/43667664/07317912-1c77-4e03-83c6-15cc38aa2b67)

**Comment by MWedl** [comment]
Good idea. Having an alternating background color for nesting levels works best (as suggested in your screenshot). We also tried to brighten the background color at every nesting level, but then deeper nested fields are hard to read.

Highlighting nested elements should be done for field definitions in designer (as in your screenshot) and also to nested form field in findings and sections (see screenshot below). 

![image](https://github.com/Syslifters/sysreptor/assets/29510012/ea8530d3-88ae-4c97-80e5-54ede786d1ec)

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.8
