### ISSUE TITLE
import failed invalid format : expected "projects/v1" got "projecttypes/v1"

### ISSUE THREAD

**Issue by anubi5egypt** [Syslifters/sysreptor#192]
import failed invalid format : expected "projects/v1" got "projecttypes/v1"

![Screenshot at 2024-01-18 05-28-05](https://github.com/Syslifters/sysreptor/assets/42506882/8dce9589-f61e-49c6-9006-0ce4c7afbf00)

**Comment by anubi5egypt** [comment]
try to add htb-designs.tar.gz nothing too 
![2024-01-18_06-45_1](https://github.com/Syslifters/sysreptor/assets/42506882/ab4ef6c7-a6a9-468b-be7e-f4e66823d6c1)
![2024-01-18_06-45](https://github.com/Syslifters/sysreptor/assets/42506882/ad4c02f1-db88-4389-8a7b-d7a463c222c8)

**Comment by aronmolnar** [comment]
In the first screenshot you're uploading a design to the projects section.
Import designs in the designs menu.

The second screenshot looks plausible and should have added the designs to SysReptor
