### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'level') in design "Customization of Matary new"  Error in render function

### ISSUE THREAD

**Issue by anubi5egypt** [Syslifters/sysreptor#194]
How can i fix this probelm
![2024-01-21_04-28](https://github.com/Syslifters/sysreptor/assets/42506882/a144f75a-ba78-48ab-a42c-322eaceaa58a)

**Comment by MWedl** [comment]
Hi,
it seems that you used a variable that does not exist in your HTML designer code. If the HTML code contains for example `finding.varname.level`, this error occurs if the variable `varname` is not available on the `finding` object. You could search for ".level" in the HTML code and check for each usage if the parent variable exists and is defined.

This is most likely an error your customized design code. Without access to this design, we are not able give you more detailed answers.
