### ISSUE TITLE
Help understanding how "Preview data" function

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#196]
I'm still a newb to Sysreptor but loving it so far.  I'm getting the hang of adding my own report fields and sections, and it looks like when I create a section for the first time, its text gets saved in the Preview Data hierarchy.  But then if you make changes to data in the Report Fields areas, that text does _not_ get pulled over into Preview Data to be rendered.  Is that correct?  Maybe my workflow is wrong, but it seems like as I edit the various sections in the Report Fields section, that should overwrite what's in Preview Data so what I see in the PDF is "fresh" ?

**Comment by aronmolnar** [comment]
Hi,
I cannot reproduce this bug.  
I made a screen record where I add a new section, new field, add it to the report HTML and update the preview data.

Maybe this helps, of you can explain where the behavior of your installations differs.

![preview](https://github.com/Syslifters/sysreptor/assets/25219407/bfc1bd69-a836-4f08-bb3e-f3551f6b170c)

**Comment by 7MinSec** [comment]
Here's the flow I was following:

1. Create a new section called goals2:
 
![image](https://github.com/Syslifters/sysreptor/assets/17596787/88282736-e64d-446a-ac8a-c70c67f5df6b)

2. When I look in Preview Data, it's populated (at the bottom):

![image](https://github.com/Syslifters/sysreptor/assets/17596787/4da96aca-5d69-47d6-951e-97531a2e1d9b)


3.  I go back into Report Fields area and change goals2 slightly:

![image](https://github.com/Syslifters/sysreptor/assets/17596787/172b00e9-48ca-43bf-8011-d6d021e16120)

4.  Back in Preview Data, the update is *not* there.  And when I render the PDF, the text for goals2 is "These are some made up goals" rather than "These are some made up goals - that are now changed!"

**Comment by MWedl** [comment]
Hi, the preview data is intended to test the design and PDF rendering without creating a new project. Preview data fields are allowed to have different values than default values. Currently, we fill the preview data fields with the field's default value only when a field is added. Afterwards the content is not automatically updated.

In #163 another user had similar problems and we discussed solutions how to improve preview data behavior.

**Comment by 7MinSec** [comment]
Thanks, I'll close this issue and comment on the other one.
