### ISSUE TITLE
Markdown editor - additional buttons

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#197]
It would be nice to have additional buttons in the markdown editors tool pane.

![image](https://github.com/Syslifters/sysreptor/assets/25219407/03d95d42-1cdc-43d1-80d6-93faa503d023)

* Checklist
* Footnote

**Comment by aronmolnar** [comment]
Another useful button would be to upload files. This would expose the image/file upload features better.

**Comment by MWedl** [comment]
Implemented buttons for checklist and footnote in https://github.com/Syslifters/sysreptor/releases/tag/2024.13
