### ISSUE TITLE
Enclose marked text (with quotes, parenthesis,...)

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#198]
If we select text in the markdown editor and want to enclose it with quotes, it would be convenient to select the text and insert the quote character, so that the text is enclosed instead of replaced.

This could be valid for:

* ()
* {}
* []
* \*
* _
* "
* '

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.13
