### ISSUE TITLE
TypeError: : Cannot read properties of undefined (reading 'count_medium') in design "HTB CPTS Report v1.0"

### ISSUE THREAD

**Issue by prokunal** [Syslifters/sysreptor#205]
I just completed my HTB CPTS report, and I have only 2 hours left to submit the report, and then i am getting errors while generating the pdf, this is really painful, if someone from Sysreptor sees this, please help.
![image](https://github.com/Syslifters/sysreptor/assets/27685644/5844bbcc-96f4-4dcb-8b72-fe6c4561c049)

**Comment by prokunal** [comment]
I didn't customize the Design, I didn't even open the designer tab once.
I checked there is not any "finding_cstats"
![image](https://github.com/Syslifters/sysreptor/assets/27685644/87820a16-b7c0-4e3a-af61-55afef238baf)

**Comment by MWedl** [comment]
Please also check if you used `{{ finding_cstats.count_medium }}` in a markdown field in any report sections or findings. The error originates from `at <Markdown>`.

**Comment by prokunal** [comment]
Thank you for your help, solved the problem.
I am also facing problem in finding from Remediation Summary, it is unable to track down the findings, like finding1.
```
* [Finding Reference 5](#findingid5) - 
```
![image](https://github.com/Syslifters/sysreptor/assets/27685644/8ebe23cc-b3db-412f-b47e-9e8495dab575)

**Comment by aronmolnar** [comment]
You need to add finding IDs (=uuids) instead of `findingidX`

https://docs.sysreptor.com/reporting/references/#reference-findings
