### ISSUE TITLE
Changes from "report.list_of_changes" to "report.document_history"

### ISSUE THREAD

**Issue by cosad3s** [Syslifters/sysreptor#207]
I have identified an incompatibility of templates for document history fields.

In the templates, the document history was named `report.list_of_changes` but now `report.document_history`.

For example, in the template, instead of:

```html
            <tr v-for="version in report.list_of_changes">
                <td>{{ version.version }}</td>
                <td>{{ version.description }}</td>
                <td>{{ formatDate(version.date, 'medium') }}</td>
            </tr>
```

You should write:

```html
            <tr v-for="version in report.document_history">
                <td>{{ version.version }}</td>
                <td>{{ version.description }}</td>
                <td>{{ formatDate(version.date, 'medium') }}</td>
            </tr>
```

**Comment by cosad3s** [comment]
It was when I re-imported my custom templates, partially based on the demo templates already embedded in Sysreptor.

**Comment by aronmolnar** [comment]
You can actually update your designs yourself.
If we make an update to any of our designs, it will have no impact on what you have locally.
