### ISSUE TITLE
Help understanding best way to handle design updates

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#209]
Hello,

I'm incessantly updating my primary report design, so it never fails that I'll be 50% through a report, and wish I could pull in all the changes I made to my master design.  Is the best way to do this:

1. Open the report I wish had the most recent changes on
2. Go to Publish > Customize Design > Customize Design for This Project
3. In HTML+VUE view and CSS tabs, manually copy and paste data from the master design

?

Only problems I could see with this is if I made structural changes (like new fields) with the master design.  Does that sound right, and/or am I doing this wrong?

Thanks,
Brian

**Comment by aronmolnar** [comment]
Every time you create a new project, your master design is duplicated for this project, as you realized. If you go to the project settings, the chosen design is then "your design from {time}".

If you have updated your master design, and want to use it for your already created project, you can use the drop down in the project settings to choose "your design".

If there were major updates in the meantime, you will receive a warning about incompatibilities.

I hope this helps.

**Comment by 7MinSec** [comment]
It does thanks much, that got me going!
