### ISSUE TITLE
Markdown H2, H3, H4

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#21]
For Markdown H2, H3, and H4 in a section. Can I add it to in-toc somehow?

Thanks

**Comment by MWedl** [comment]
The `<table-of-contents>` component looks for headlines with the class `in-toc` and automatically includes them in the table of contents.

Unfortunately, settings classes via native markdown syntax is not supported yet. In the next release we will add support for setting HTML attributes with following syntax:
```markdown
## Heading 2 {.in-toc}
```

For now you can embed HTML tags in markdown to achieve the same result. Make sure to leave a blank line before and after the HTML code such that it gets parsed correctly.
```markdown
markdown `code`

<h2 class=".in-toc">Heading 2</h2>

markdown `code`
```

**Comment by vysecurity** [comment]
Oddly enough, I tried this and it doesn't seem to add it to the TOC.
