### ISSUE TITLE
Traceback error caused by corrupt(?) config.yaml

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#211]
Hi,

I'm loving sysreptor so as part of my pentest box build process, I have `pip3 install reptor` fire, and then the Kali box also pulls down a `config.yaml` file from a Web site.

After getting this all set tonight, when I ran `reptor` I got this:

<img width="864" alt="image" src="https://github.com/Syslifters/sysreptor/assets/17596787/18c1a5d5-bf9e-4b02-99c3-827979dbfe00">

After a ton of fruitless troubleshooting, I tried nuking the `config.yaml` I pulled down as part of the build process.  Then reptor ran fine.  I went back to my `config.yaml` on the Web site and resaved it as "Unix(LF)" instead of "Windows (CR LF)" and then reptor was totally happy with that and ran fine!

**Comment by aronmolnar** [comment]
I cannot reproduce this error. Reading the config with CRLF and LF both work fine for me (on both, Windows and Linux).

Can you provide us your (redacted) config file as you downloaded it from your web site?

**Comment by 7MinSec** [comment]
Shoot sorry, I fixed the hosted version and didn't save the broken one.  I'll close this for now and reopen if/when I can recreate.
