### ISSUE TITLE
Markdown code block color highlighting

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#22]
Hi there,

Any way to highlight certain parts of a code block in markdown with a different color? For example:

```
GET /?request=abc HTTP1/.1
XXXXX
```

I want to highlight request=abc. I tried things like asterisk, and backticks.

It helps to be able to point out the payload in a request.

**Comment by MWedl** [comment]
Yes. See https://docs.sysreptor.com/reporting/markdown-features/#code-blocks

````markdown
```http highlight-manual
POST /login.php HTTP/1.1
Host: sqli.example.com
Content-Type: application/x-www-form-urlencoded
Content-Length: 33

§§username='or'1'='1§§&password=dummy
```
````

**Comment by vysecurity** [comment]
I read the docs, thanks.

**Comment by MWedl** [comment]
You can add CSS rules for the HTML `<mark>` tag

```css
mark {
    background-color: red;
}
```

**Comment by vysecurity** [comment]
Works wonders! Thankyou.
