### ISSUE TITLE
Option to disable "Encrypt report PDF" by default

### ISSUE THREAD

**Issue by firefart** [Syslifters/sysreptor#220]
It would be nice to have a system wide config option to disable the "Encrypt report PDF" checkbox on the publish page per default. Currently it's enabl;ed by default and needs to be disabled each time if you don't want or need encryption.

**Comment by aronmolnar** [comment]
This could be one option.
Another would be to store the last applied setting in the local storage and apply this, maybe?

**Comment by firefart** [comment]
yes that’s also an option. just something that doesn’t require unchecking it on each report

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.28

The last applied "Encrypt report PDF" setting is remembered in the browser's local storage.
