### ISSUE TITLE
Can you change default format for pasted images?

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#221]
Hello!

I really like the image formatting option you mention in your docs - something like:

```
<figure style="border: 1px solid #0099dc;">
  <img src="/images/name/image-52008.png">
  <figcaption>Here is my caption</figcaption>
</figure>
```

Is there any way to make this the *default* paste template instead of...

```
![](/images/name/image-52008.png){width="auto"}
```

?

Thanks!
Brian

**Comment by MWedl** [comment]
It is not possible to change the default image format. From your example, I assume your goal is to add a border around all images. Applying borders and other styling elements can be achieved using CSS rules in the design. Using CSS is the recommended way to adapt formatting and styling, instead of inline HTML in markdown and inline styles.

For example, you can add following CSS rule to your design to add borders around every figure:
```css
figure {
    border: 1px solid #0099dc;
}
```

**Comment by 7MinSec** [comment]
Hello, this gets me most of the way there.  Only picky thing is I really like having the border and caption under all pics in the findings section, but DON'T want border or findings under some imagery earlier in the report where I talk about methodology, etc.  I'm sure with a little more boilerplate work on my main template I can strike a happy medium pretty easily.  

Thanks again for all the great work with Reptor.  I'm *really* close to my happy place where I am literally writing a near-finished version of the report as I test because Reptor allows me to work so quickly with the CLI and copy+paste screenshotting.  LOVE IT.

**Comment by MWedl** [comment]
You can use CSS selectors to apply the figure-border rules only to parts of the document. For example, to only apply image borders to specific sections (e.g. findings list, executive summary, etc.) use following CSS rules. Figures that are outside the selected sections use the default figure styles (CSS selection `figure {}`).

```css
#findings-list figure, #executive-summary figure {
    border: 1px solid #0099dc;
}
```

In HTML you need to set section IDs which are used to select the sections in CSS. Alternatively you could also use CSS classes for this.
```html
<section id="executive-summary">...</section>
<section id="findings-list">...</section>
```
