### ISSUE TITLE
Option to export findings as PDF separately

### ISSUE THREAD

**Issue by danymat** [Syslifters/sysreptor#222]
Hello Everyone,

Thank you for this super duper tool. I'm following this project since the beginning, and will maybe plan on using it.

I have one feature request: have an option to export findings for a report in separate pdfs.
This process is very handy when developers need to have only the vulnerability finding they are supposed to fix. 

By giving them only the pdf for their vulnerability, we can store this PDF alongside other ones and give access to the vulnerability finding only to relevant people for remediation purposes, without giving them all the report.

Did you already think of that ? If no, what is the possibility of adding it as an option ? 
Else, do you already have an API endpoint we could play with, that could allow to perform this request ?

**Comment by aronmolnar** [comment]
Hi danymat,
Thanks for your suggestion.

If you export one finding per report, you will still have the cover page, ToC, management summary, appendices, etc., in your report. 
With that in mind, you can add a boolean finding field (e.g., `hide`) that is evaluated in your report design and prevents findings from being rendered into the report if set to true.

You could also add a boolean report field (e.g., `minimal_report`) that eliminates the cover page, management summary, etc.  
An alternative might be to duplicate your design and have two separate designs for your full report and individual findings.

You can automate this process by creating a plugin for [reptor](https://docs.sysreptor.com/cli/getting-started/) that iterates through all findings, sets all `hide` flags to true, except for one, and to render and download the report using an alternative design ([you can do](https://docs.sysreptor.com/cli/projects-and-templates/project/) the last step using `reptor project --render -o report.pdf --design 0222cdf1-4208-491c-8a23-7d49d67707ff`).

If that's a feasible solution, we can support you with the reptor plugin.

**Comment by danymat** [comment]
Hello,

That's a wonderful idea. 
My take would be to set `hide=true` to all findings (except the one), as well as `minimal_report=true`, and iterate as you said.
I should not forget to set the flags to false at the end :)

I will try to play locally with that idea in mind, and contribute with a plugin for reptor as soon as I get something cool (still trying out with sysreptor beforehand)

I will update you here + on reptor for news, thanks !!

**Comment by aronmolnar** [comment]
You can take a look at the [PushProject](https://github.com/Syslifters/reptor/blob/main/reptor/plugins/projects/PushProject/PushProject.py) plugin.

Example:
```
cat """{
  "findings": [
    {
      "data": {
        "summary": "My Summary #1"
      }
    },
    {
      "data": {
        "summary": "My Summary #2"
      }
    }
  ]
}""" | reptor pushprojects
```

This currently adds the specified findings as new findings.  
I suggest to create a new plugin (e.g., "UpdateFindings") that doesn't create new findings, but updates the existing ones.

**Comment by danymat** [comment]
Hello, just to update that the idea was perfect :)

The idea we used was to have a `show` boolean field, all set to False.
The plugin does 2 iterations on the findings:
- The first iteration change all `show` fields to False
- The second iteration change the `show` field to True, render the finding with a custom design, and re-set to False.

Thanks !!
