### ISSUE TITLE
UI: Squished Buttons in Publishing Tab

### ISSUE THREAD

**Issue by StephanPillhofer** [Syslifters/sysreptor#229]
Small UI improvement:

The buttons during publishing of a report are vertically squished together and not aligned when dragging the pane smaller. I only notice it all the time because I usually split my window with Sysreptor on one side and another program on the other.

![grafik](https://github.com/Syslifters/sysreptor/assets/43667664/6a4a2b8d-3e9e-4670-9af9-79ba67972944)

**Comment by MWedl** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2024.28
