### ISSUE TITLE
Issue saving files to sysreptor via HTTP?

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#232]
Hi,

I've got sysreptor setup in an internal lab to show during a Webinar.  Following some tips you gave me in [this issue](https://github.com/Syslifters/sysreptor/issues/191), I setup Sysreptor to listen on all interfaces on port 8000.

From a separate linux box, I installed reptor and if I do something like `cat kerberoast.json | reptor finding` it adds to the report perfectly.  However, if I try to `cat test.txt | reptor file` it gets attached as a `data.dat` file (in this screenshot I've tried several different text files, all very small in size):

![image](https://github.com/Syslifters/sysreptor/assets/17596787/c7c58a76-c0fc-47b7-bed1-d3c645c181b7)

Adding files using this method on my "real" report server (secured with LetsEncrypt HTTPS) works great, so the only difference I can see here is I have no HTTPS setup in the lab, so maybe something is getting screwed up by way of that during transfer?

**Comment by 7MinSec** [comment]
One thing I just noticed - if I actually download the `data.dat` file and view in notepad, the contents are in tact.  So technically the attachments are working, but seem like they should pop up as `name-of-file.txt` instead of `data.dat`.

**Comment by MWedl** [comment]
Hi,
when passing files via stdin, the filename is not available to `reptor`. Only the file contents are passed to the stdin stream. `data.dat` is used as a fallback if not filename can be inferred.

In order to set a filename for uploaded files, you can either explicitly set the filename when uploading from stdin:
```shell
cat name-of-file.txt | reptor file --filename=name-of-file.txt
```

Or (more conveniently) pass filenames as arguments instead of stdin. With this method, the filename is available to `reptor` and will be automatically set.
```shell
reptor file name-of-file.txt
```

**Comment by 7MinSec** [comment]
Ah that makes sense.  I swear I was doing the `cat file.txt | reptor file` in assessments and the past and it was working, but the `reptor file file.txt` is absolutely working.  Thanks much!  

P.S. I did a livestream yesterday showing my love of Sysreptor and walking through how quickly teams can get spun up with it.  https://www.youtube.com/watch?v=DGjXXQgoXXc.  Thanks for an awesome service!

**Comment by aronmolnar** [comment]
Very nice, thank you very much Brian.
Apart from the positive feedback, it's always great to see how other people work with SysReptor. And this also gives me (and us) some new ideas how to further improve (I've got a good list of items after watching :) ).

Thanks!
