### ISSUE TITLE
Feature Request - Show all Projects to Admin users without Superuser mode

### ISSUE THREAD

**Issue by firefart** [Syslifters/sysreptor#233]
Currently an Admin/Superuser can only see all projects when switching to superuser mode (or if the account is added to all projects by hand). It would be nice to have this maybe configurable in the settings, so Admins can see all projects without enabling god mode.

Might be related to https://github.com/Syslifters/sysreptor/issues/150 if there is a more general solution to this

**Comment by MWedl** [comment]
We decided to implement the solution proposed in #150 instead. Superusers with admin mode not enabled will still not be able to access projects they are not member of. Users with "Project Admin" permissions can access all projects without having to enable the permission. It will be possible to assign superusers the "Projects Admin" permission to access all projects without having to enable admin permissions.
