### ISSUE TITLE
Login issue on Ubuntu: Either a Key or a multiple available keys must be given

### ISSUE THREAD

**Issue by silent6trinity** [Syslifters/sysreptor#234]
After rebooting my machine, stopping containers/restarting containers or updating sysreptor, I receive the following error whenever trying to login. I've tried troubleshooting this issue for a few hours now and am going insane, lol:

I've even reset the password multiple times to _ensure_ im doing this right - still no avail

![image](https://github.com/Syslifters/sysreptor/assets/78173918/03f10555-1d68-4544-8af3-3a77a88b2936)

**Comment by silent6trinity** [comment]
To add to this, it seems like this is only occuring if the username _doesnt_ have a "." in the username.

![no dot in username](https://github.com/Syslifters/sysreptor/assets/78173918/e3688da3-5574-49a0-9421-9dbe295496d7)

![same password, dot in username](https://github.com/Syslifters/sysreptor/assets/78173918/e25aa3c6-456a-48e8-b251-ba8163898ce9)

**Comment by aronmolnar** [comment]
Hi Ibby,

The error indicates that there are issues with decrypting data from your database.  
Sensitive data at rest is encrypted using a secret from your `app.env` file:

![image](https://github.com/Syslifters/sysreptor/assets/25219407/8738dfa5-5adb-4bae-93b0-e9c55ffc000b)

The `app.env` should be in the `sysreptor/deploy` directory and is referenced in the `docker-compose.yaml` as env file.

**Comment by aronmolnar** [comment]
Maybe you started the docker container manually.

If you use `docker compose -f docker-compose.yml up -d` the `app.env` should be mounted (if present in that directory).

**Comment by silent6trinity** [comment]
No, that doesn't seem to work. I've tried that a few times - including copying over a *known good* `app.env` file, and it still causes this issue.

**Comment by aronmolnar** [comment]
The error strongly indicates that your encryption keys are missing.

You can verify that the encryption keys are present via `docker exec sysreptor-app env`:

![image](https://github.com/Syslifters/sysreptor/assets/25219407/bd01394e-6389-40e8-9b1c-a9af69e53a68)

**Comment by guillaumerosin** [comment]
Je rencontre actuellement le même problème

**Comment by aronmolnar** [comment]
Can you please post the contents of the variables ENCRYPTION_KEYS and DEFAULT_ENCRYPTION_KEY_ID from the command `docker exec sysreptor-app env` executed in the `deploy` directory?  
Please redact the actual key, but not the key ids.

**Comment by guillaumerosin** [comment]
ENCRYPTION_KEYS=[{"id": "e07e7872-8aad-4e59-ad69-dd472dff6701", "key": "J/bhU2q3g9emq0+9NBqeKFYxGkAzzRYMVAUo5M9Jsgk=", "cipher": "AES-GCM", "revoked": false}]

DEFAULT_ENCRYPTION_KEY_ID=e07e7872-8aad-4e59-ad69-dd472dff6701

![image](https://github.com/Syslifters/sysreptor/assets/142811942/d617ac92-2d5c-4bc9-afd2-c68fe0c78c43)

**Comment by guillaumerosin** [comment]
Je vous avais envoyé un mail justement à ce propos si vous souhaitez me recontacter : guillaume.rosin@risk-horizon.be

**Comment by aronmolnar** [comment]
For the sake of documentation: The errors were different.

silent6trinity had the error 'Either a key or a multiple available keys must be given' which indicates that there was no key in the environment.  
guillaumerosin had the error 'Metadata contains unknown key_id. Cannot find a suitable key for decryption.' which indicates that a key was present but decryption failed because it was the wrong key.
