### ISSUE TITLE
Reference customer name in markdown

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#24]
Hi there,

How would you reference the cusotmer's name in markdown?

```
We attacked {{report.customer}} ...?
```

**Comment by aronmolnar** [comment]
This is the right variable:

![image](https://github.com/Syslifters/sysreptor/assets/25219407/5f9782c7-166b-4a31-8af4-1217b93359a2)

`{{ report.customer_name }}`

**Comment by vysecurity** [comment]
Oh I typed it wrong.!

**Comment by MWedl** [comment]
Just like in your example :)

It is not rendered in the preview for security reasons (we don't want template injections there). However, template variables are rendered in the final PDF. This feature, however, is quite experimental and not all variables are supported yet.

**Comment by vysecurity** [comment]
Turns out doesn't render in preview, which is a little bit of a pain.
