### ISSUE TITLE
Field does not have a remove option

### ISSUE THREAD

**Issue by brunomcuesta** [Syslifters/sysreptor#245]
Hello!
I have a field "title" that I want to remove, but the removal icon does not appear. Is it a bug?

![image](https://github.com/Syslifters/sysreptor/assets/816237/cf8693fd-3680-46dc-bffd-913a10df2a8f)

Sysreptor version: 2024.30

Thanks!

**Comment by aronmolnar** [comment]
Hi,

This is intentional. The data structure requires that a report has a title (it's meant to be the report title, not the Appendix title).

**Comment by brunomcuesta** [comment]
Ok!
Thanks!
