### ISSUE TITLE
Weird with text and screenshots

### ISSUE THREAD

**Issue by suljov** [Syslifters/sysreptor#246]
Hello, while testing doing a report with a CTF etc i saw some of my text/"code snipets" and screenshots dont really look like it should do

examples

1:
![image](https://github.com/Syslifters/sysreptor/assets/24814781/37bd4461-e7b2-4be6-ab9b-0505064ef5f3)

2:
![image](https://github.com/Syslifters/sysreptor/assets/24814781/42a073b0-fd73-46c9-b353-201808899978)

3:
![image](https://github.com/Syslifters/sysreptor/assets/24814781/b7ed0024-1061-42b6-b90b-cafe4ed23ccc)

the screenshots are not centered and dont really fit etc. some code snipets are long and suddenly goes outside the report.

**Comment by MWedl** [comment]
Hi,
text and image overflow can be configured with CSS rules in the design.

What design are you using? Is it based on an example design or a custom one?

If it is a custom design, we recommend to add `@import "/assets/global/base.css";` at the top of your design's CSS code. This line imports some base styles that provide useful default behavior, which you might want to use in most report designs. The base styles also contain rules to prevent images and code blocks from overflowing pages.

If you do not want to import all base styles you can selectively copy some rules from https://github.com/Syslifters/sysreptor/blob/main/api/src/reportcreator_api/tasks/rendering/global_assets/base-text.scss to your design's CSS code. However, we recommend to include the whole base styles.
