### ISSUE TITLE
[Feature requested] Download as Office Word .docx format

### ISSUE THREAD

**Issue by trnayan** [Syslifters/sysreptor#249]
[sysreptor](https://github.com/Syslifters/sysreptor) is a great reporting tool. However, I believe it would be even more beneficial if there were an option to export the report in .docx format.

**Comment by aronmolnar** [comment]
Thank you.
This would, however, be a different project.

It could be addressed by implementing docx support in Weasyprint or by converting PDFs to word (there are some solutions, like from Adobe).

This is, however, unfortunately out of scope of this project.
