### ISSUE TITLE
Dates show hanging numbers in Select Date pop out.

### ISSUE THREAD

**Issue by Gray-0men** [Syslifters/sysreptor#251]
Noticed some random numbers showing up in the dates to the left of Sunday's dates, cosmetic issue nothing major.
![image](https://github.com/Syslifters/sysreptor/assets/39830524/3f9a1574-4163-4dad-9219-4cecc9b87bf3)

Also noticed the Nessus reptor usage has a typo in the Docs, the usage example has "--filter-severity" instead of "--severity-filter"
![image](https://github.com/Syslifters/sysreptor/assets/39830524/1d54c96a-e132-48ef-ad39-6cf68138b03a)

**Comment by MWedl** [comment]
> Noticed some random numbers showing up in the dates to the left of Sunday's dates, cosmetic issue nothing major.

These are week numbers.

> Also noticed the Nessus reptor usage has a typo in the Docs, the usage example has "--filter-severity" instead of "--severity-filter"

Thanks for noticing. I have updated the documentation. It will be published at the next release. The correct one is `--severity-filter`.
