### ISSUE TITLE
Easy way to create an asset-to-finding table at end of report?

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#258]
Hello,

We've got a huge Web pentest project we're working on with tons of sites and also tons of the same vulnerabilities.  To make reporting simple, we're going to have a report with:

* Finding
* Affected Assets
* Details on finding, etc.

At the end of the report though, we'd like to have an asset-to-finding table to make it easier for them to see the remediations that need to be done per site, i.e.:

* **Finding: cross-site scripting**
* Affected assets:
  * Site 1
  * Site 3
  * Site 5

* **Finding: SQL injection**
* Affected assets: 
  * Site 2
  * Site 4
  * Site 6

Could you steer me in the right direction?

**Comment by aronmolnar** [comment]
Hi Brian,

I created you a sample code for such a table:

![image](https://github.com/Syslifters/sysreptor/assets/25219407/3d5881e6-6ad1-46c2-9b58-111a20e2f9b4)

It uses the title and the `affected_components` field and also adds the page number to the table.
Rows are also linked.

```
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Affected Assets</th>
            <th>Page</th>
        </tr>
    </thead>
    <tbody>
        <template v-for="finding in findings">
            <tr class="table-row-link">
                <td>
                    <a :href="'#' + finding.id">{{ finding.title }}</a>
                </td>
                <td>
                    <template v-if="finding.affected_components.length === 0"></template>
                    <template v-else-if="finding.affected_components.length === 1"><a :href="'#' + finding.id">{{ finding.affected_components[0] }}</a></template>
                    <template v-else>
                        <template v-for="s in finding.affected_components"><a :href="'#' + finding.id">{{ s }}</a></template>
                    </template>
                </td>	
                <td>
                    <a :href="'#' + finding.id" class="finding-pagenumber"></a>
                </td>
            </tr>
        </template>
    </tbody>
</table>
```

**Comment by 7MinSec** [comment]
Thank you!  This is really close - there are two things I have questions about:

* The affected assets show as one continuous string - i.e. "AffectedSite1.comAffectedSite2.com" - should they be comma-separated?

* Page number column is there but no page numbers for each finding.

Sorry these might be super basic fixes, but I'm a code newb.

**Comment by aronmolnar** [comment]
Hi,

For the page number you might not have a CSS element that I had. Add this to your CSS specs and it should work:

```
.finding-pagenumber::after {
    content: target-counter(attr(href), page);
    text-decoration: none;
    color: initial;
}
```

And I also missed to provide you the CSS snippet for table-row-link, which adds line breaks between your affected components:

```
tr.table-row-link a {
    display: block;
}
```

**Comment by 7MinSec** [comment]
NICE!  This looks super great, much appreciated!

**Comment by 7MinSec** [comment]
Ah sorry one more small ask/tweak!  In my table the affected asset field often looks like this:

```
www.domain.co
m
```

I tried to set table width to 100% in CSS but this doesn't help.  It seems like the Title column wraps at around 45 characters, but I'd like to have it so the affected asset URL always stays in tact without wrapping:

```
www.domain.com
```

**Comment by aronmolnar** [comment]
Can you try the `white-space: nowrap;` css style?
(See https://stackoverflow.com/a/1893764)

**Comment by 7MinSec** [comment]
This appears to be working - all I did was change `<table>` to `<table style="white-space:nowrap;">` and the links look good now.  Much appreciated!
