### ISSUE TITLE
Feature Request: No output on backup command

### ISSUE THREAD

**Issue by firefart** [Syslifters/sysreptor#265]
When running `manage.py backup` even with the `-v 0` parameter, this string is always printed: `2024-05-29 15:46:07,042 [INFO] root: Backup requested`

Feature Request: This string should only printed on more verbose levels so the backup task can be integrated more easily into cron jobs

**Comment by MWedl** [comment]
The `-v` flag was not implemented for the `manage.py backup` command (but django always adds a `-v` CLI option). We will respect the `-v` flag in the next release.

**Comment by MWedl** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2024.49
