### ISSUE TITLE
Docs: Backup site should include --rm switch

### ISSUE THREAD

**Issue by firefart** [Syslifters/sysreptor#266]
The backup site over here https://docs.sysreptor.com/setup/backups/ should include the `--rm` switch on the `docker compose run` commands. This way there are no stale containers left behind.

**Comment by MWedl** [comment]
Good suggestion, thanks. We will update the docs.

**Comment by MWedl** [comment]
Updated docs in https://github.com/Syslifters/sysreptor/releases/tag/2024.49
