### ISSUE TITLE
Users page accessible without superuser mode

### ISSUE THREAD

**Issue by firefart** [Syslifters/sysreptor#269]
When accessing `/users` without superuser mode enabled (with a user that has superadmin rights) the userlist is shown and users can be viewed, alltough the Users option in the sidebar is greyed out.
Not sure if this is a bug or just a display problem as the user has the rights to view them. I haven't tried it with a non priviledged user.

This occured because when you disable superuser permissions when on the users page, the page is still shown but without last login dates.

**Comment by MWedl** [comment]
This is just a display problem. Users are listed, but not all fields are shown. For unprivileged users, the API only returns user names, but not permission infos, last login, etc.
