### ISSUE TITLE
Change Label Font of Chart

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#27]
Hi there,

I have a chart as shown below:

![Opera-2023-05-13 at 00 03 30@2x](https://github.com/Syslifters/sysreptor/assets/3596242/fb2e463f-76e8-41b2-bfe0-d37d4c97a554)

I am wondering how to change the font?

**Comment by MWedl** [comment]
The `<chart>` component is a wrapper for the library Chart.js. I think you can configure the font in the options. Please see the Chart.js documentation: https://www.chartjs.org/docs/latest/

**Comment by noraj** [comment]
https://www.chartjs.org/docs/latest/general/fonts.html

**Comment by aronmolnar** [comment]
As an example:

```
<chart :width="15" :height="10" :config="{
        type: 'bar', 
        data: {
            labels: ['Critical', 'High', 'Medium', 'Low', 'Info'],
            datasets: [{
             data: [
               finding_stats.count_critical,
               finding_stats.count_high,
               finding_stats.count_medium,
               finding_stats.count_low,
               finding_stats.count_info
             ],
             backgroundColor: ['#FF2600', '#FF9300', '#FFDA00', '#0096FF', '#00AE51'],
           }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true,
                    ticks: {
                        precision: 0,
                    }
                },
                x: {
                    ticks: {
                        font: {
                            size: 50,
                            family: 'Noto Sans',
                            weight: Bold
                        }
                    }
                }
            },
            plugins:
            {
                legend: {display: false}
            }
        }
      }" />
```

![image](https://github.com/Syslifters/sysreptor/assets/25219407/36bd06cb-5a02-4aeb-b2f8-58566f680fae)

**Comment by aronmolnar** [comment]
Here's a list of fonts that come preinstalled on the server side:

* Noto Sans
* Noto Serif
* Noto Mono
* Open Sans
* Roboto
* Roboto Serif
* Lato
* Exo
* Tinos
* Source Code Pro
* Roboto Mono
* Courier Prime

Hope this helps :)
