### ISSUE TITLE
update.sh breaks execute right / crontab docu update

### ISSUE THREAD

**Issue by byteboltsec** [Syslifters/sysreptor#276]
Hi syslifters,

when running `update.sh` via cronjob (or manually), it pulls the `source-prebuilt.tar.gz` when there is a new update but breaks the update procedure, because the `update.sh` will be overwritten and can't be executed anymore.
Currently the `source-prebuilt.tar.gz` is shipped without execute right, only the `generate_notice.sh` has the execution flag:

```bash
# tar -ztvf source-prebuilt.tar.gz
...
-rw-r--r--  0 root   root     3864 18 Jun 09:26 sysreptor/update.sh
-rwxr-xr-x  0 root   root    39235 18 Jun 09:26 sysreptor/api/generate_notice.sh
...
```

Maybe ship the `update.sh` in the tarball with execution rights or put a check in the script itself would be nice :)

I have also found an issue with the docs for the auto update. Calling the script in the crontab like:
```
0 0 * * * /bin/bash /home/yourpath/sysreptor/update.sh
```
wouldn't set the variable `BIND_PORT` when the IP bind was changed and would break the access via reverse proxy.
Calling the script via a login shell would work when the `BIND_PORT` was put e.g. in `.profile`:

```
0 0 * * * /bin/bash -l -c "/home/yourpath/sysreptor/update.sh"
```

Hope that helps! :)

```
Ubuntu 24.04 LTS
Linux sysreptor 6.8.0-36-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 10 10:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Docker 26.1.4
```

**Comment by aronmolnar** [comment]
Thank you for reporting this.  
Yes we will update this and clarify in the docs how to retain the BIND_PORT value.

**Comment by aronmolnar** [comment]
https://github.com/Syslifters/sysreptor/commit/3bc66b4aa4ff19f62b8ffbd480204ba477aaaf74

**Comment by MWedl** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2024.55
