### ISSUE TITLE
Expected behavior after export/import to a new Sysreptor instance?

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#277]
Hi!

Proud new sysreptor Pro user here :-)

I installed the Pro license, did an export from my old Sysreptor instance into a new VPS.  Worked like a champ.

When I logged in with my 7MS user and went to edit a master template, it said I didn't have permission.  I hit the option for "Enable superuser permissions" and it logged me out.  I logged in and then had superuser permissions and then I could see/do all the things.

However, once I log out, I'm back to "regular" permissions again and have to go through the "Enable superuser permissions" routine again.  Is this expected?  When I look at `Administration > Users` my permissions are `Superuser`

Thanks,
Brian

**Comment by aronmolnar** [comment]
Hi Brian,

Yes, this behaviour is expected.  
If a user logs in, the user is in an unprivileged mode. Using the "Enable superuser permissions" the user gets administrative permissions, if the user has the "Superuser" role.

It's the same as working with an unprivileged user in a terminal and elevating the permissions using "sudo".

The reasons behind it are 1. security and 2. that customers don't need to license additional users for administrative tasks: They can work with their user and elevate their permissions if needed.

**Comment by 7MinSec** [comment]
Ok sure that makes sense.  Thanks!
