### ISSUE TITLE
Code block padding

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#28]
Hi there,

I tried many times and many ways to try reduce this code block's padding around the text.

![Opera-2023-05-14 at 01 23 42@2x](https://github.com/Syslifters/sysreptor/assets/3596242/24cf028b-dc32-45ca-b6c3-74cbf6f88cb8)

Any idea how to reduce that to a bit smaller?

**Comment by noraj** [comment]
In the CSS editor:

![image](https://github.com/Syslifters/sysreptor/assets/16578570/90420ab4-9a1f-46fe-b205-700a163c4449)

**Comment by vysecurity** [comment]
Appreciated. Will give it a go!

**Comment by vysecurity** [comment]
Worked!
