### ISSUE TITLE
"Could not establish WebSocket connection"

### ISSUE THREAD

**Issue by SGTAn0nY** [Syslifters/sysreptor#280]
After a recent update, when loading into a project in SysReptor, we get the error shown in the screenshot, stating that no connection to the WebSocket could be established.

However, everything seems to be running properly and be set up according to the documentation. We especially looked at the "caddy" reverse proxy and restarted the Docker container that runs it, but that sadly did not fix it.

Thanks in advance to everyone.

![sysreptor_issue](https://github.com/Syslifters/sysreptor/assets/46885140/7d15f493-6c9c-4429-901a-7a4c722d31f7)

**Comment by aronmolnar** [comment]
Hi,
There were some changes in a recent updates due to a WebSocket hijacking vulnerability.

You will probably be able to resolve this issue by setting the "ALLOWED_HOSTS" variable to your hostname, e.g. `ALLOWED_HOSTS="sysreptor.example.com"` (you can add multiple hostname, comma-separated).
