### ISSUE TITLE
Languagetool installation fails because of missing slash in Dockerfile

### ISSUE THREAD

**Issue by StephanPillhofer** [Syslifters/sysreptor#285]
The Docker installation for the languagetool fails because of a missing `/` in its Dockerfile:

Wrong:
`COPY scripts/* .`

Correct:
`COPY scripts/* ./`

Inserting the slash fixes the problem.

Docker Version: 27.0.3

![grafik](https://github.com/Syslifters/sysreptor/assets/43667664/c856cd4a-eb32-45db-a972-b601aa7f3de1)

**Comment by MWedl** [comment]
Thanks for reporting. We will update the Dockerfile

**Comment by MWedl** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2024.57
