### ISSUE TITLE
No restart policy for redis docker service

### ISSUE THREAD

**Issue by c3sro** [Syslifters/sysreptor#293]
There is no `restart` policy defined for the redis docker service in https://github.com/Syslifters/sysreptor/blob/d92087536e3da9e503041b82915bd1c0ff3821cc/deploy/docker-compose.yml#L27
So it defaults to `no` (see: https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy)

After a host reboot the redis service won't start and some errors in GUI appear (`Could not establish WebSocket connection`) until docker-compose is manually executed again.

Would it be possible to add `restart: unless-stopped` (like already done for the other services)?

**Comment by aronmolnar** [comment]
Thanks for reporting.
We'll do.

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.60
