### ISSUE TITLE
reptor exportfindings function type error

### ISSUE THREAD

**Issue by tagnullde** [Syslifters/sysreptor#296]
When using `reptor exportfindings --format toml` we get the following error:

![sysreptor_bug](https://github.com/user-attachments/assets/da5b322e-0c73-4e16-a36e-21f753488fbd)

After digging into the error a bit, it looks like the `gen_table_chunks` function is expecting a dict but receives a list.

On a side note, `reptor exportfindings --format json` has also some issues but we haven't looked into that any deeper.
The CSV export seems to work fine.

**Comment by aronmolnar** [comment]
Thanks for reporting.

We fixed the issue in the latest release:
* https://github.com/Syslifters/reptor/releases/tag/0.21
* https://pypi.org/project/reptor/

You can upgrade using `pip3 install --upgrade reptor`
