### ISSUE TITLE
[Feature Request]: Add deploy/docker-compose.pro.yml

### ISSUE THREAD

**Issue by firefart** [Syslifters/sysreptor#297]
It would be great to add a `deploy/docker-compose.pro.yml` file containing an include of the languagetool compose file as the override file is now deprecated. This way it's easier to build the images in a CI pipeline without the need to manually edit the existing file.

**Comment by aronmolnar** [comment]
We restructured the structure of docker-compose files to make deployments easier.

After the update you just installed, you still have the docker-compose.override.yml for the languagetool. With the next update you execute, the override file will be deleted and the line `  - include: languagetool/docker-compose.yml` will be added to your main docker-compose.yml

(see also: https://docs.sysreptor.com/setup/upgrade-to-professional/)

You can freely edit your main docker-compose.yml and it will be transferred when doing updates.

So there should not be a need for a dedicated docker-compose.pro.yml

**Comment by firefart** [comment]
The benefit (at least for us) would be to build the docker images in a ci pipeline (with a fresh git checkout) without editing the existing files or running `install.sh`. Directly specifying the `./deploy/languagetool/docker-compose.yml` file with `-f` also does not work because of the relative path included which will be applied to PWD (and thus require a higher level docker-compose.yml which includes this file). So in a CI environment the only option without using the (still available) `docker-compose.override.yml` is to manually create a new file or modify the existing one to include the language tool.

**Comment by firefart** [comment]
Thanks that works
