### ISSUE TITLE
Mermaid formatting not exported to pdf

### ISSUE THREAD

**Issue by tagnullde** [Syslifters/sysreptor#299]
In one of our recent reports, we used the mermaid functionality to draw a pie chart.
We did some coloring on it, but it wasn't exported to the pdf.

The markdown preview showed it, correctly though.

This is the markdown view:
![image](https://github.com/user-attachments/assets/aa8da539-ecdb-4696-a88b-49b8908f30a6)

This is the same pie chart exported to the pdf.
![imagebw](https://github.com/user-attachments/assets/4da05c26-62a6-4696-b954-4c197f805f33)

The expectation was, that formatting that's done in the markdown editor and successfully rendered in the preview will then also work when exported to the pdf.

**Comment by MWedl** [comment]
Thanks for reporting. We will fix this bug in the next release.

The problem was that curly braces inside the mermaid code block were not properly decoded while rendering. This resulted in the `init` block not being applied.

**Comment by MWedl** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2024.63
