### ISSUE TITLE
Installation on ARM-based VMs

### ISSUE THREAD

**Issue by 000wl** [Syslifters/sysreptor#30]
Helll and first of all thank you for this amazing project.

I would like to take advantage of it as I will be doing OSCP training soon but I am facing some issues due to the fact I don't have a x64 VM.

First, I had issues when installing the dependencies, so I changed the version of _FROM python:3.10-slim-bullseye_ for one ARM version in the **Dockerfile**.

After that, I had to include _&& pip3 install Django_ after RUN _pip3 install -r requirements.txt_ in the **Dockerfile** also as it couldn't find when running manage.py. 

And now I have the following error that I was not able to fix...
<img width="989" alt="Screenshot 2023-05-14 at 17 44 54" src="https://github.com/Syslifters/sysreptor/assets/133588715/26bf79fd-23a3-4f58-b967-fa6c5b0a7b6f">

Could you please let me know if I missed something ? 
Thank you in advance.

**Comment by aronmolnar** [comment]
The problem is that we pinned the base images by the exact hash. We will fix that in one of the next releases.

In the meantime you can go to the Dockerfile and remove the hash of the python base image:

`FROM python:3.10-slim-bullseye AS api-dev`

**Comment by 000wl** [comment]
Thank you a lot @aronmolnar, it works incredibly good. 

Cheers!
