### ISSUE TITLE
Password Reset?

### ISSUE THREAD

**Issue by ILikeToHelp** [Syslifters/sysreptor#301]
Hey, I can't seem to find a way to reset my password on https://labs.sysre.pt/login/local/. 
I tried 'signing-up' again, hoping it would bring up 'you already have an account, click here for forgot password' but it seems that's not the case.

Thanks!

**Comment by aronmolnar** [comment]
Hi,
You observed correctly.  
There is no possibility to reset passwords at SysReptor due to security reasons.

You can send us an email to hello@syslifters.com using the email address that you used and we can reset the password for you.
