### ISSUE TITLE
Note Export as PDF does not check checkboxes

### ISSUE THREAD

**Issue by danymat** [Syslifters/sysreptor#311]
Hello, 

I found a weird bug:

Notes exported as PDF do not check the checkboxes in the rendered PDF file:

In note:
![image](https://github.com/user-attachments/assets/051dbe94-39c6-4987-b8fc-f9a04a63cfe3)

In rendered PDF:
![image](https://github.com/user-attachments/assets/1b5ef185-af52-434f-8418-add6d9e9d7dc)

**Comment by MWedl** [comment]
Hi,
thanks for reporting. We will fix this in the next release.

**Comment by aronmolnar** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2024.69
