### ISSUE TITLE
{{report.testingco}} does not appear correctly if next to <pagebreak/>

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#312]
Hi,

I am one version away from the latest so this might've already been squashed, but I notice in my template if I have something like this:

```
<pagebreak/>
Blah blah {{report.testingco}} found total pwnage...
```

In the actual report, the variable will appear as `{{report.testingco}}` and not 7 Minute Security.  However, if I just have an extra blank line after the `<pagebreak/>`, the name gets parsed correctly.

In the template:

![image](https://github.com/user-attachments/assets/3a62b6c8-fc57-4a47-80e1-18f497ce0087)

In the actual report:
![image](https://github.com/user-attachments/assets/e9f2a5bc-dff3-4e99-9c9d-1828379719d6)

**Comment by MWedl** [comment]
Hi,
the empty line is required to separate the HTML block from markdown text. Without the empty line, the text is treated as part of HTML and template variables are not resolved. Unfortunately, this is a "feature" of the CommonMark spec. Similar to #310.

**Comment by 7MinSec** [comment]
OK makes sense thanks!
