### ISSUE TITLE
Managing images

### ISSUE THREAD

**Issue by Talha-Kircili** [Syslifters/sysreptor#317]
After inserting images to a finding, where are the images stored and how can one delete / modify these. Is it possible to do it via the Web-Ui? A tool to crop images would be also highly appreciated.

**Comment by MWedl** [comment]
Hi, SysReptor manages images in the background. Images that are no longer referenced in findings (or sections or notes) are deleted by a scheduled task. Modifying images is currently not implemented. You can, however, delete the old image reference from markdown text and upload a new image version.
