### ISSUE TITLE
Custom CA error

### ISSUE THREAD

**Issue by c3sro** [Syslifters/sysreptor#319]
When trying to import a custom CA according to https://docs.sysreptor.com/setup/configuration/#custom-ca-certificates an error occurs:
```
sysreptor-app           | /app/api/start.sh: line 3: /usr/local/share/ca-certificates/custom-user-cert.crt: Permission denied
sysreptor-app           | Updating certificates in /etc/ssl/certs...
sysreptor-app           | /usr/sbin/update-ca-certificates: 101: cannot create /etc/ssl/certs/ca-certificates.crt.new: Permission denied
```

TLS Connection depending on this CA won't work.

Affected version: 2024.69

**Comment by aronmolnar** [comment]
Thanks for reporting this issue. We will fix it in the next release.

**Comment by aronmolnar** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2024.70
