### ISSUE TITLE
CSS Vertical Text not working

### ISSUE THREAD

**Issue by richardschwabe** [Syslifters/sysreptor#32]
Following CSS code did not work:
```
writing-mode: vertical-rl;
text-orientation: mixed;
```

Reference:
https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation

I got vertical text working by using transform though, it is not pretty:
```
.vertical{
  display: inline-block;
  transform: rotate(90deg);
  transform-origin: left top 0;
  margin:0;
  padding:0;
  margin-left:20px;
  width:100px;
  top:-20px;
  position: absolute;
}
```

Setup: docker compose self hosted
browser: Google Chrome

**Comment by MWedl** [comment]
Unfortunately, the CSS `writing-mode` rule is not supported yet by Weasyprint (HTML+CSS to PDF rendering library). For now you have to stick to your workaround :(
