### ISSUE TITLE
Issue Disabling Users

### ISSUE THREAD

**Issue by enoir3** [Syslifters/sysreptor#323]
When logged in with a user and after activating superuser permissions, I cannot deactivate another active user (not the currently logged-in user).

We've run into a max licensing issue. While waiting for additional licenses to proceed up and down the procurement process, we want to disable a user to free up the license for a new pentester that joined our team. I have removed all roles from the target user and ensured they have been removed as members from all active projects, but still cannot uncheck the "User is active" box.

**Comment by aronmolnar** [comment]
There are two circumstances in which the field should be greyed out:

* Your user doesn't have the permissions (which doesn't seem to be the case)
* The target user is a "system" user

You can see in the user overview if your target user is a system user:
![image](https://github.com/user-attachments/assets/55b7a411-c942-41ef-a969-cd4866066433)

If this is the case, you could elevate your privileges to superuser, go to `/admin/users/pentestuser/`, select the target user and remove the system user permissions. You should also be able to disable the user there.

**Comment by enoir3** [comment]
The target user is not a System user, and I have removed all of their other roles and active projects. It seems like I can't uncheck the "User is active" checkbox.
![active user](https://github.com/user-attachments/assets/79aaa06a-352f-4463-b615-8cee19dab0d8)

**Comment by aronmolnar** [comment]
Can you uncheck the tick via the Django admin at `/admin/users/pentestuser/`?

![image](https://github.com/user-attachments/assets/1c9c95c3-d9dd-4e83-bcc6-f3bd945153fe)

**Comment by enoir3** [comment]
I did not realize you could access the back-end Django in that manner. That worked perfectly for me, much appreciated!
