### ISSUE TITLE
Add button to export to Microsoft Word

### ISSUE THREAD

**Issue by zachi40** [Syslifters/sysreptor#325]
Would it be possible to add a feature to download the report in .docx format instead of .pdf? 
This would give to me more flexibility in editing the reports after downloading.

thank you

**Comment by aronmolnar** [comment]
Hi,
This is more complex than just adding a button and, unfortunately, out of scope of this project (see also: https://github.com/Syslifters/sysreptor/issues/249).

The tech stack is not suitable, docx not an open and reliable document specification.  
You can try to convert your exported report to docx using other tools (like Adobe Acrobat).
