### ISSUE TITLE
DEMO DATA

### ISSUE THREAD

**Issue by trnayan** [Syslifters/sysreptor#330]
How to import/use the demo data ? Can anyone help?

**Comment by MWedl** [comment]
Hi,
the git repository contains demo data definitions in TOML format. SysReptor, however, requires .tar.gz files to import. We provide pre-built .tar.gz files for demo data managed in this repository at `https://docs.sysreptor.com/assets/{folder-name}.tar.gz` (where `{folder-name}` is the name folder name in `demo-data/*` e.g. `https://docs.sysreptor.com/assets/htb-designs.tar.gz`). You can import these .tar.gz files via the web interface (upload button in project/design/template lists) or via a docker compose command (see https://docs.sysreptor.com/htb-reporting-with-sysreptor/ for an example).

**Comment by aronmolnar** [comment]
```
# Projects
url="https://docs.sysreptor.com/assets/demo-projects.tar.gz"
curl -s "$url" | docker compose exec --no-TTY app python3 manage.py importdemodata --type=project --add-member="$username"

# Designs
url="https://docs.sysreptor.com/assets/demo-designs.tar.gz"
curl -s "$url" | docker compose exec --no-TTY app python3 manage.py importdemodata --type=design

# Finding templates
url="https://docs.sysreptor.com/assets/demo-templates.tar.gz"
curl -s "$url" | docker compose exec --no-TTY app python3 manage.py importdemodata --type=template
```
