### ISSUE TITLE
Funky word wrap on long descriptions in change log table

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#332]
Hello!

I'm finding that if I make a long description in a change log and it wraps to a second line, it scrunches the date column together a bit:

![image](https://github.com/user-attachments/assets/5af7f038-6b57-486c-8402-04be0f997e93)

Super minor thing, but is there some html/css hack I can do when inserting this longer description so that the date would stay in tact without wrapping?

**Comment by MWedl** [comment]
Hi, there is in fact a CSS rule for this: setting a fixed width for the date column. You can define a CSS class in the design or add the rules to the `style` inline HTML attribute.

```css
.table-changelog-date {
    table-layout: fixed;
    width: 6em;
}
```

```html
<table>
  <tr>
    <th class="table-changelog-date">Date</th>
    ...
  </tr>
  ...
</table>
```

**Comment by aronmolnar** [comment]
For this case you could also use this CSS

```
.table-changelog-date {
    white-space: nowrap;
}
```

**Comment by 7MinSec** [comment]
This works, thanks for the great replies as always!
