### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by MWedl** [Syslifters/sysreptor#338]
Allow extending the functionality of the SysReptor web application.

Requirements:
* extend backend and frontend functionality
* load plugins dynamically at start (not at build time)
* enable/disable plugins via settings
* register API routes
* store models in database tables (with migrations)
* listen to django signals (e.g. project created)
* add pages to frontend
* add menu entries (e.g. main menu, project menu)
* add/modify CSS styles

**Comment by aronmolnar** [comment]
Yes we will.  
We now implemented three official plugins (CyberChef, GraphQL Voyager, Hash Identifier) that are rather simple and do not integrate into the core SysReptor functionality.  
The next plugin we're working on (should be released with the next update) is webhooks on certain events.

Developing official plugins first allows us to find deficiencies and complexities in the plugin system before documenting the plugin system for public use. There might also be breaking changes in the system in the next releases. (Even though using the plugin system would be possible already.)

As the next step, we will document, how to enable the existing plugins and we'll notify you here as soon as this is available.
