### ISSUE TITLE
Design Preview Data - History Authors not populated correctly

### ISSUE THREAD

**Issue by richardschwabe** [Syslifters/sysreptor#34]
Expected:
Access the users in the history of a report during design creation and use the preview data to print out the author.

Reality:
The authors are not populated, resulting into NULL and therefore an empty string in the template.

Steps to reproduce:

- Do not have users populated, keep the default installation with user reptor (without names,or other infos)
- Create a new design.
- Then add the reptor as a user into the history. 
- Is not populated in the HTML. 

Furthermore, if you add another user and populate the fields for the names, it is also not offered in the preview data.

User Setup:
![image](https://github.com/Syslifters/sysreptor/assets/63605187/8b4f74da-1a4a-419d-a309-1c85b1a61b34)

Preview Data;
![image](https://github.com/Syslifters/sysreptor/assets/63605187/4ccdd2ae-f6c0-44d4-b6f4-8a6ff3e98080)

HTML:
![image](https://github.com/Syslifters/sysreptor/assets/63605187/65c60a6c-fef5-43d0-8736-4a626a6e91e0)

Setup: docker compose local
Browser: Chrome

**Comment by MWedl** [comment]
Thanks for the info. We will fix this bug in the next release.

**Comment by richardschwabe** [comment]
I played around with it a bit more and this is the case for the User Field in general. 

Also when you create a custom User-type field.

**Comment by MWedl** [comment]
Yes, you are right. I also notices this while investigating and fixing the bug :) 
The problem was an error in fetching and formatting the user object for template rendering in `format_template_field_user()`. We used the ID from the User-type field wrong in this function, which resulted in an invalid DB query that never returns a result.
