### ISSUE TITLE
Help finding source of "cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#345]
Hello,

I just worked on a big Web app pentest report with about a dozen findings.  I went to render the PDF and get this rather vague message:

![image](https://github.com/user-attachments/assets/c3e56c63-1a72-430a-9877-3f6e100189e1)

I haven't changed my template for weeks so I don't actually think the problem lies within the template, but probably within a malformed finding somewhere.  Any ideas on how I can get more verbose logging and figure out where the problem is, short of deleting and re-adding one finding at a time (REALLY don't want to do that if I can avoid it)?

Thanks,
Brian

**Comment by MWedl** [comment]
Hi,
unfortunately Vue does not provide meaningful error location information for runtime errors. 

The error results from accessing `{{ xxx.value }}` where the variable `xxx` (or `report.xxx`) is undefined. You can search for `.value` in finding texts. Please note that in findings you can only use report fields as variables with an absolute path (`report.xxx`), not fields of the current finding (`finding.xxx`).

You could also modify the design and add a checkbox field to finding fields that selectively hides findings. This is probably faster than deleting and re-adding findings.

**Comment by 7MinSec** [comment]
Thanks Michael I'll keep this in mind.  My findings had a ton of URLs and bulleted lists with single ticks and quotes.  I went through each one to turn them into "final" copy, and when I did that and refreshed the PDF all was well.  Going forward I think I'll just be more careful to take a look at the PDF preview between findings so I'm not trying to find a needle in a haystack.
