### ISSUE TITLE
Fix Docker Compose Command in docs/docs/install.sh

### ISSUE THREAD

**Issue by br484** [Syslifters/sysreptor#346]
**Description**:  
There are multiple instances in the installation script `docs/docs/install.sh` where the Docker Compose command syntax `docker compose` (with a space) is used. However, for compatibility across environments, it should consistently use `docker-compose` (with a hyphen). This mismatch can cause errors in environments where Docker Compose v2 or the Docker CLI plugin are not configured to recognize `docker compose`.

**Problematic Lines**:
- **Line 25**:
   ```bash
   ! docker compose version >/dev/null 2>&1
   ```
   Change to:
   ```bash
   ! docker-compose version >/dev/null 2>&1
   ```
- **Line 158 and others**:
   Each occurrence of `docker compose` (e.g., in `docker compose up -d`, `docker compose exec`, etc.) should be replaced with `docker-compose` for compatibility.

**Suggested Fix**:
Standardize the command by replacing all instances of `docker compose` with `docker-compose`. This will ensure compatibility and prevent runtime errors in environments without the Docker Compose plugin.

**Comment by aronmolnar** [comment]
`docker compose` is the recommended Docker v2 syntax:

> Unlike Compose V1, Compose V2 integrates into the Docker CLI platform and the recommended command-line syntax is `docker compose`.

https://docs.docker.com/compose/releases/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2

**Comment by br484** [comment]
Thank you, @aronmolnar , for the response and for clarifying the recommended syntax for Docker Compose v2. I apologize for my misunderstanding.

In my environment, I had to use the docker-compose syntax with the hyphen due to the version I’m running, and it resolved my compatibility issues. I appreciate the guidance

**Comment by aronmolnar** [comment]
Thanks for your feedback and happy to hear you could resolve your issue.
