### ISSUE TITLE
[Feature Request] Automatic Design Updates

### ISSUE THREAD

**Issue by DevPentest** [Syslifters/sysreptor#347]
When updating design templates, any open/non-final projects with the design attached are not automatically updated. It would be a convenient feature to have it always synced up with the latest design upon saving edits to the design for the project.

Also, clearing design history from the project - can this be done easily?

**Comment by aronmolnar** [comment]
This behaviour is intended.
When a user creates a project, SysReptor creates a copy of the selected design (this copy creates a "Design XY from 2024-10-30" - which I think you refer to as "design history"). You can delete these designs via the Django interface at https://yoursysreptor/admin/pentests/projecttype/ or by exporting and re-importing your project.

This behaviour makes sure that if you create a PDF report for your customer at one point in time, you can reproduce the exact same report, months or years later, even if the design has changed or became incompatible.

**Comment by MWedl** [comment]
The main idea behind design snapshots was to prevent unexpected changes of old projects when the design changes and also prevents data loss when a field is deleted from the design or the field data type is changed.
