### ISSUE TITLE
[Feature Request] 2FA Support Toggle

### ISSUE THREAD

**Issue by DevPentest** [Syslifters/sysreptor#348]
Could a way be added to disable 2FA prompts upon logging in via app.env setup file and/or superuser settings?

**Comment by MWedl** [comment]
For non-privileged users (without superuser permissions - available in SysReptor Pro), the 2FA setup prompt only pops up once after the first login. For superusers, the 2FA prompt is shown at every login. We try to nudge superusers into enabling 2FA to better protect their accounts.
