### ISSUE TITLE
[Feature Request] Image Watermarking

### ISSUE THREAD

**Issue by DevPentest** [Syslifters/sysreptor#349]
Feature request to supports watermarking images that are uploaded to a finding. For instance if we wanted a confidential banner on passwords cracked to signify sensitivity. Other ideas:
- Top/bottom/edge banners
- Transparent horizontal/vertical/diagonal banners

Not sure if this type of feature would also be transferable to rendered codeboxes, too.

**Comment by MWedl** [comment]
Simple banners should be possible via CSS rules (e.g. as overlay) during PDF rendering. Adding banners to the actual image files is not possible.

You could try `img::before` or `figure::before` elements to set the `content` text or a background image for the banner and apply positioning rules. This approach would also work for code boxes. We haven't tried this, though.
