### ISSUE TITLE
Plugin: Webhooks at certain events

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#353]
We have a request from a Professional customer who needs webhooks at certain events, in special:

* Create Project
* Create Finding
* Finish Project
* Archive Project
* Delete Project

Each webhook should include the action (e.g., "finish_project") and metadata (e.g., the project ID, finding ID).  
It must not contain sensitive information.

SysReptor could trigger Django signals that the plugins handle and execute their logic (like sending a web hook).  
The complex part about this is that plugin logic execution blocks the corresponding HTTP requests (e.g., triggered by users). If the webhook runs into a timeout, the client request would be unresponsive until the timeout is hit.  
The webhooks must, therefore, run asynchronously.

Another issue is SSRF which might allow attackers to send HTTP requests to internal systems. Attackers, however, could only control an API token (or request headers?) and the target endpoint. They wouldn't have access to response data or response time (if the request is done asynchronously). We could accept this risk.

**Comment by aronmolnar** [comment]
The remote server should handle tasks that are triggered by webhooks asynchronously if they can take longer (e.g., 1s or more). SysReptor might close the connection if the remote server keeps it open. (We might want to add this information to documentation.)

Additionally, we should provide the possibility to test webhooks. I suggest to offer a Django management command, so that webhooks can be triggered for testing purposes from the command line.

**Comment by schue30** [comment]
It would be nice if the webhook request to the remote server contains an HTTP header with a shared secret or a signature of the request. This allows the remote server to check whether the webhook request actually comes from SysReptor.

A nice optional feature would also be a retry mechanism in case the remote server cannot be reached.

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2024.96 as plugin.

See https://github.com/Syslifters/sysreptor/blob/main/plugins/webhooks/README.md for details how to configure and use webhooks.
