### ISSUE TITLE
Help with adding a user when I'm out of licenses (but not really)?

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#355]
Hi,

I have three users in my Pro tenancy - 2 of which are currently disabled as I'm troubleshooting an issue I'm having:

I'm trying to add a new tester to work on some reports with me and Sysreptor says I'm out of licenses and need to deactivate some users.  As mentioned, only my account is enabled, but I noticed in my license page that it says my max amount of users is 1.  That isn't right, is it? 

Brian

**Comment by aronmolnar** [comment]
Handled via official support channel.
