### ISSUE TITLE
[Feature Request] Add Finding Fields created_at & updated_at

### ISSUE THREAD

**Issue by Lednerb** [Syslifters/sysreptor#358]
For a recent project it would be very useful to have access to a finding's meta data like timestamp / date_time values for the events `created_at` and ideally also `updated_at`.

My idea is the following:
Counting and sorting findings if they were `created_at` before or after a specific date.

Further context:
Actually I want to group the findings if they are added in the original penetration test or in a re-audit later on.
For my workflow I have a reporting field `is_reaudit`, so I can duplicate pentest reports and toggle the checkbox to work in _re-audit mode_.

**Comment by MWedl** [comment]
The finding creation timestamp is already available as variable.
```html
<div v-if="new Date(finding.created) <= new Date(report.retest_date)">
```

I noticed that `finding.created` is only set for actual project findings, but not for preview data in the PDF designer. We will set it there too, such that it is consistent. 

The `finding.updated` timestamp is not very useful IMO, because it is updated whenever a finding field changes. This also includes internal fields (e.g. finding order), or when the finding is duplicated (together with project).

**Comment by Lednerb** [comment]
Ah thanks for the explanation @MWedl!

It's correct, I could not find it within the PDF designer section by outputting all finding fields.
I'm looking forward for the addition :+1:

**Comment by Lednerb** [comment]
Just as a quick validation:

If I have my original Pentest Report with findings, each finding gets a value for `created`.
If I duplicate the original report for a re-audit, the findings still have the original `created` value or will this value be overwritten by the duplication date?

**Comment by Lednerb** [comment]
> The finding creation timestamp is already available as variable.
> 
> ```
> <div v-if="new Date(finding.created) <= new Date(report.retest_date)">
> ```
> 
> I noticed that `finding.created` is only set for actual project findings, but not for preview data in the PDF designer. We will set it there too, such that it is consistent.
> 
> The `finding.updated` timestamp is not very useful IMO, because it is updated whenever a finding field changes. This also includes internal fields (e.g. finding order), or when the finding is duplicated (together with project).

## :exclamation:  Just for future reference

I've struggled a lot with one finding that was not properly selected by just doing the following:

```html
<div v-if="new Date(finding.created) <= new Date(report.retest_date)">
```

The issue in this approach (at least on my side) was, that `new Date(report.retest_date)` is not always the **whole day**, so I had to adjust the logic to the following:

```html
<div v-if="new Date(finding.created) <= new Date(new Date(report.past_report_dates[0]).setHours(23,59,59,999))">
```


The additional `new Date` wrapper is needed because the format changes after `.setHours` was used.

**Comment by MWedl** [comment]
Fixed setting `finding.created` in design preview in https://github.com/Syslifters/sysreptor/releases/tag/2024.96
