### ISSUE TITLE
[Feature Request] Singular docker image for self-hosting

### ISSUE THREAD

**Issue by FortTheStrox** [Syslifters/sysreptor#360]
So currently for self-hosting users, they need to have an Ubuntu OS to do the docker "easy install". And do a command to install some library dependencies then curl the install script which creates the 4 docker containers needed to run the app. 

What I'm requesting is if we can consolidate it from 4 containers to just a singular container where it's an ubuntu image which the 4 components installed into it (caddy, postgres db, redis, etc). Thus, when spinning it up, it's just a singular container and can be spun up regardless of the host OS as well. This also reduces the amount of startup commands to just 1 command (provided the user already has docker installed).

**Comment by MWedl** [comment]
Hi,
running multiple services inside a single container is against the philosophy of containerized applications. Generally, it is recommended to run each service in a separate container.

The easy install script should work for distributions other than Ubuntu, if the required dependencies are installed. When the easy install script detects that some dependencies are missing, it prompts the Ubuntu installation instructions. However, if you are using another distribution, you can install the equivalent packages for your distro and rerun the easy install script.

The main task of the easy install script is to interactively generate the initial SysReptor config and download the latest release from GitHub. You could also perform these steps manually and run `docker compose up`.

**Comment by FortTheStrox** [comment]
Oh okay, fair enough!
