### ISSUE TITLE
Impossible to update

### ISSUE THREAD

**Issue by farheinheigt** [Syslifters/sysreptor#365]
**Issue Description:**
When I tried to launch the update script, it failed with the following error message:
"docker compose v2 is not installed."

**Solution:**
I resolved the issue by modifying the script and replacing all occurrences of docker compose with docker-compose.

**Environment Details:**
macOS
OrbStack and Docker installed via Homebrew
Let me know if you need more details.

**Comment by aronmolnar** [comment]
Hi Farid,
Thanks for the ticket.

This is indeed not an issue as the error message indicates that you have the wrong docker compose version (v1) installed.
We recommend using the latest docker version (v2) which you can install using Docker Desktop for Mac (see https://docs.docker.com/desktop/setup/install/mac-install/).

As, from time to time, users run into this issue, we might want to update our install and update script to support both syntaxes.  
We cannot, however, officially support the legacy version. So we should print a warning that docker v2 wasn't found and the scripts might not work as intended..
