### ISSUE TITLE
Installation Error When `chmod +x /app/api/download_fonts.sh`

### ISSUE THREAD

**Issue by nikotidar** [Syslifters/sysreptor#37]
Installation failed in
```sh
=> ERROR [api-dev 5/9] RUN chmod +x /app/api/download_fonts.sh && /app/api/download_fonts.sh
=> CANCELED [frontend 1/1] RUN npm run build
------
> [api-dev 5/9] RUN chmod +x /app/api/download_fonts.sh && /app/api/download_fonts.sh:
------
failed to solve: process "/bin/sh -c chmod +x /app/api/download_fonts.sh && /app/api/download_fonts.sh" did not complete successfully: exit code: 8
```

<img width="1469" alt="Screen Shot 2023-05-24 at 12 36 38 AM" src="https://github.com/Syslifters/sysreptor/assets/49534825/9c6d6418-b494-4ba1-97e8-b73b1580fff2">

**Comment by aronmolnar** [comment]
I suspect, there is an error downloading the fonts from Google.
Can you confirm that this might be the reason? You can test if the download works with `wget https://fonts.google.com/download?family=Roboto`
