### ISSUE TITLE
failed to solve: process "/bin/sh -c chmod +x /app/api/download_fonts.sh && /app/api/download_fonts.sh" did not complete 

### ISSUE THREAD

**Issue by puzzithinker** [Syslifters/sysreptor#45]
=> ERROR [api-dev  6/10] RUN chmod +x /app/api/download_fonts.sh && /app/api/download_fonts.sh                                                                                                 2.7s
------
 > [api-dev  6/10] RUN chmod +x /app/api/download_fonts.sh && /app/api/download_fonts.sh:
#0 0.361 Downloading Open Sans from https://fonts.google.com/download?family=Open+Sans
#0 1.177 Downloading Roboto Flex from https://fonts.google.com/download?family=Roboto+Flex
#0 1.777 Downloading Roboto Serif from https://fonts.google.com/download?family=Roboto+Serif
------
failed to solve: process "/bin/sh -c chmod +x /app/api/download_fonts.sh && /app/api/download_fonts.sh" did not complete successfully: exit code: 8
Ups. Something did not work while bringing up your containers.

**Comment by aronmolnar** [comment]
I suspect, there is an error downloading the fonts from Google.
Can you confirm that this might be the reason? You can test if the download works with wget https://fonts.google.com/download?family=Roboto+Serif

(We might resolve this issue by self hosting the fonts in the future.)

**Comment by AndroxNZ** [comment]
I was also receiving this same error all yesterday. Manually trying to download https://fonts.google.com/download?family=Roboto+Serif was resulting in a 500 error from Google, "There was an error. Please try again later. That’s all we know."

As the error suggested, I tried again later and it was magically resolved. I was then able to run the script and have it finish successfully. 

Funny enough. hours later I've gone back and tried again to manually download https://fonts.google.com/download?family=Roboto+Serif and I'm back to receiving the 500 error. So I wouldn't be surprised if this is causing installation issues for plenty of people.
