### ISSUE TITLE
User removal

### ISSUE THREAD

**Issue by noraj** [Syslifters/sysreptor#5]
By error, I created an extra user, there is no way to remove it from the WebUI.

![image](https://user-images.githubusercontent.com/16578570/236927772-8b3887a0-b492-4bc7-967b-680621545915.png)

- Workaround 1: set user as Inactive and remove all roles
- Workaround 2: connect to DB and remove it manually with SQL (could be dangerous if not inherited properly)

Solution: add a delete user button.

**Comment by aronmolnar** [comment]
Thanks for the suggestion.

As another workaround you can delete the user from the Django Backend at: https://syslifters.sysre.pt/admin/users/pentestuser/

**Comment by MWedl** [comment]
Added button to delete users to the user management UI in https://github.com/Syslifters/sysreptor/releases/tag/0.83
