### ISSUE TITLE
Feature to export the Notes markdown to PDF

### ISSUE THREAD

**Issue by franklinpshaw** [Syslifters/sysreptor#54]
Hello,
Can we please have a feature to export the markdown 'Personal Notes' to PDF?

**Comment by aronmolnar** [comment]
Hello,
we'll have a look how this could be best implemented.
Definitely a feature that should be there.
Thanks!

**Comment by franklinpshaw** [comment]
> Exported in the same document or separately?

I think it should be each note separately right?

**Comment by aancw** [comment]
> > Exported in the same document or separately?
> 
> I think it should be each note separately right?

I agree. Maybe need export button in every note.

![CleanShot 2023-07-10 at 17 54 32@2x](https://github.com/Syslifters/sysreptor/assets/6284204/bd7d127e-8d8b-4c8a-93eb-4d7d0797b481)

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2023.114

You can trigger the PDF export in the context menu of notes.
![Screenshot_20230809_152400](https://github.com/Syslifters/sysreptor/assets/29510012/cc2ee221-d36d-48e8-b28d-3bfee98951b9)
