### ISSUE TITLE
Feature Request - convert finding to template

### ISSUE THREAD

**Issue by Moneysac90** [Syslifters/sysreptor#57]
Currently it is not possible to convert a finding into a template. This function is useful because otherwise all fields of a finding have to be copied manually into a template.

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/0.110

**Comment by aronmolnar** [comment]
![template_from_finding](https://github.com/Syslifters/sysreptor/assets/25219407/9bfb82d9-89d6-4052-a29e-858fcec23b62)
