### ISSUE TITLE
Feature Request - Possibility to change design files for each project

### ISSUE THREAD

**Issue by Moneysac90** [Syslifters/sysreptor#58]
Currently, it is not possible to directly change the design of a project. If your customer has specific needs (e.g. an additional chapter, change of colors or a different order of the sections), it is not possible to make such changes in the project. The only way is to change the entire design even if the change only applies to one specific project. 

When you open the designer you have access to the Vue.js and CSS files. I am suggesting the same if you open the project tab. As far as I am aware the design is copied when you create a new project. So it should be very easy to give users access to those files (Vue.js + CSS) in the project tab.

**Comment by cmahrl** [comment]
There is such a feature. You'll find a "Customize Design" button in the reporting tab of your project. If you create a custom design, you will then see a project specific design tab where you can make necessary adaptions.
The button should probably be moved to the Project Settings to be more visible, though. Possibly where the design selection is as well.
