### ISSUE TITLE
Version page

### ISSUE THREAD

**Issue by noraj** [Syslifters/sysreptor#6]
It would be handy to have a `/version` page with a link into the user menu (like for license) that would display the version information about sysreptor.

Maybe a security consideration would be to limit access to superuser only.

**Comment by aronmolnar** [comment]
We'll add the version to the license page (/license) which is accessible for superusers.

**Comment by MWedl** [comment]
https://github.com/Syslifters/sysreptor/releases/tag/0.83 shows the current software version in license page (/license).
