### ISSUE TITLE
Feature request / help: Alternate severity ratings

### ISSUE THREAD

**Issue by HufferSec** [Syslifters/sysreptor#60]
My company currently does not opt to use CVSS for most testing as we don't believe it is the best approach for most clients. Currently we have a custom finding field that lets us set the rating manually, however, this then messes with stuff like count_critical which is super useful for graphs. 

My request is either can there be alternative rating methods supported OR can someone guide me on how to dynamically plug these numbers into the graph?

**Comment by aronmolnar** [comment]
Hi, thanks for this issue.

Fully understand this.
Currently, the CVSS field is mandatory for each finding. Sorting of issues also happens via this field.

CVSS will be optional in the future. We will probably provide an alternative risk score field (which might be an enum with the same risk scores CVSS defines, like None, Low, Medium, High, Critical).  
It should also be possible to define by which field issues should be sorted. Manual sorting of issues should also be possible.

This is one of the next things we will implement.

It might be worth waiting for this feature for you?

Would it be a feasible temporary solution to use CVSS (even though you don't have to use the vector and the exact score in the report) and just set the values that result in the score you would like to set?

Then, you would have an up to five-scale rating. You could even replace the names in your report (like 'if "critical" then "extraordinary").

**Comment by MWedl** [comment]
It is possible to use your custom rating in charts by calculating the finding count per severity level via a JavaScript expression.
The `finding_stats` variable in the design is just a convenient shortcut that performs the calculations in the background.

Following example uses an enum field `custom_rating` for severity levels to render a chart.
```html
<chart :width="15" :height="10" :config="{
    type: 'bar', 
    data: {
        labels: ['Critical', 'High', 'Medium', 'Low', 'Info'],
        datasets: [{
            data: [
                findings.filter(f => f.custom_rating.value === 'critical').length,
                findings.filter(f => f.custom_rating.value === 'high').length,
                findings.filter(f => f.custom_rating.value === 'medium').length,
                findings.filter(f => f.custom_rating.value === 'low').length,
                findings.filter(f => f.custom_rating.value === 'info').length,
            ],
            backgroundColor: [
                cssvar('--color-risk-critical'), 
                cssvar('--color-risk-high'), 
                cssvar('--color-risk-medium'), 
                cssvar('--color-risk-low'), 
                cssvar('--color-risk-info')
            ],
        }]
    },
    options: {
        scales: {y: {beginAtZero: true, ticks: {precision: 0}}}, 
        plugins: {legend: {display: false}},
    }
}" />
```

**Comment by HufferSec** [comment]
> ```
>                 findings.filter(f => f.custom_rating.value === 'critical').length,
>                 findings.filter(f => f.custom_rating.value === 'high').length,
>                 findings.filter(f => f.custom_rating.value === 'medium').length,
>                 findings.filter(f => f.custom_rating.value === 'low').length,
>                 findings.filter(f => f.custom_rating.value === 'info').length,
> ```

This is exactly what I needed! Thanks :)
