### ISSUE TITLE
Add datalabels plugin for Chart.js

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#61]
This will allow us to create labels with percentages in the pie-diagrams etc.

* https://chartjs-plugin-datalabels.netlify.app/
* https://github.com/chartjs/chartjs-plugin-datalabels

License is MIT.

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2023.114

ChartJS plugins are disabled by default. You can enable them in designs for each chart separately by adding the plugin to the chart config.
```html
<chart :config="{plugins: [chartjsPlugins.DataLabels], ...}" />
```
