### ISSUE TITLE
Install fails using the latest release

### ISSUE THREAD

**Issue by Trailingslashes** [Syslifters/sysreptor#63]
Running the curl command from the docs produces an error.

```
curl -s https://docs.sysreptor.com/install.sh | bash                                               
Good to see you.
Get ready for the easiest pentest reporting tool.

Downloading SysReptor from https://github.com/syslifters/sysreptor/releases/latest/download/source-prebuilt.tar.gz ...
Checking download...
Unpacking sysreptor.tar.gz...
Creating app.env...
Generating secret key...
Generating data at rest encryption keys...
No license key found. Going with Community edition.
Creating docker volumes...
Volume: sysreptor-db-data
Volume: sysreptor-app-data
Build and launch SysReptor via docker compose...
We are downloading and installing all dependencies.
This may take a few minutes.
unknown shorthand flag: 'f' in -f
See 'docker --help'.

```

**Comment by aronmolnar** [comment]
You are probably using podman instead of docker, or an outdated docker version.

Can you try to install docker following the guide at: https://docs.docker.com/engine/install/ubuntu/

**Comment by Trailingslashes** [comment]
I was running this on arm. That's probably not supported. 

```
docker version        
Client:
 Version:           20.10.25+dfsg1
 API version:       1.41
 Go version:        go1.20.6
 Git commit:        b82b9f3
 Built:             Mon Jul 17 08:24:02 2023
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.25+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       5df983c
  Built:            Mon Jul 17 08:24:02 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.20~ds1
  GitCommit:        1.6.20~ds1-1+b1
 runc:
  Version:          1.1.5+ds1
  GitCommit:        1.1.5+ds1-1+b1
 docker-init:
  Version:          0.19.0
  GitCommit:        

```

**Comment by aronmolnar** [comment]
The latest docker compose plugin should also have the f-switch on arm AFAIK.

**Comment by Trailingslashes** [comment]
Here's my docker-compose version 
```
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.11.4
OpenSSL version: OpenSSL 3.0.9 30 May 2023
```

**Comment by aronmolnar** [comment]
This is docker-compose (instead of "docker compose"), which is no longer supported by docker.
Can you install the compose plugin in v2?

https://docs.docker.com/compose/migrate/

(We will try to find a solution that our script also works with compose v1)

**Comment by aronmolnar** [comment]
I could reproduce the error.

It looks like you don't have docker compose in v2 installed (you can verify using `docker compose`, which should return an error).  
You should be able to install it via apt. Those are the commands from the latest documentation:

```
# uninstall all conflicting packages
for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do apt-get remove -y $pkg; done

# Install prerequisites
apt-get update
apt-get install -y ca-certificates curl gnupg

# Add GPG key
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

# Add sources list
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null
  
# Install docker and compose plugin
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

**Comment by aronmolnar** [comment]
However, we might want to adapt our script that it works with docker v1 too (obviously there are many people having problems to correctly install the latest docker version).

We actually tried to check if "docker compose" is installed but there is a bug in https://github.com/Syslifters/sysreptor-docs/blob/15aaad8f744410600dd198263eec7ca81607a832/install.sh#L13. We would need to enclose the `cmd` variable in double quotes.

If `docker compose` does not exist, but `docker-compose` does, we could map `docker compose` to `docker-compose`:

```
if ! command -v "docker compose" >/dev/null
then
    if ! command -v "docker-compose" >/dev/null
    then
        # docker compose and docker-compose not installed
        echo "docker compose not found"
        echo "Follow the installation instructions at https://docs.docker.com/engine/install/ubuntu/"
    else
        # Map "docker compose" to "docker-compose"
        echo "docker compose v2 not found. Will use v1 instead."
        docker() {
            if [[ $1 == "compose" ]]; then
                shift  # Removes "compose" from argument list
                docker-compose "$@"
            else
                command docker "$@"
            fi
        }
    fi
fi
```

Currently, our docker-compose.yml would not be compatible, because we use `name` as top-level variable at https://github.com/Syslifters/sysreptor/blob/47937ce6689d37931d655d7d00dfa4c6ad75970d/deploy/docker-compose.yml#L2

We could remove this line and add `-p sysreptor` to our `docker compose up` commands, which is supported by both, compose v1 and v2.

The install script could be at the earliest updated at the next release, when `name` was removed.


This change would also require us to update https://github.com/Syslifters/sysreptor/blob/main/update.sh (otherwise, users could install SysReptor, but not update).

What do you think @MWedl ?

**Comment by aronmolnar** [comment]
Fixed check in https://github.com/Syslifters/sysreptor-docs/blob/a57a78af612de85ac2d6883ca7faf5c288e0e7ce/install.sh#L13.

**Comment by jmhickman** [comment]
Might the check above have broken something else?

```
user@reptor:~# docker compose version
Docker Compose version v2.20.2
user@reptor:~# curl -s https://docs.sysreptor.com/install.sh | bash
Good to see you.
Get ready for the easiest pentest reporting tool.

Error: docker compose is not installed.
Follow the installation instructions at https://docs.docker.com/engine/install/ubuntu/
```

**Comment by Patralos** [comment]
> Might the check above have broken something else?
> 
> ```
> user@reptor:~# docker compose version
> Docker Compose version v2.20.2
> user@reptor:~# curl -s https://docs.sysreptor.com/install.sh | bash
> Good to see you.
> Get ready for the easiest pentest reporting tool.
> 
> Error: docker compose is not installed.
> Follow the installation instructions at https://docs.docker.com/engine/install/ubuntu/
> ```

Yes, you are right this can't work, as compose is a subcommand of docker and not a standalone binary.

I removed the check for now, so you are able to install sysreptor without problems. We will fix it on monday :)

**Comment by jmhickman** [comment]
Confirmed, seems to be running the installer now. Thanks!

**Comment by aronmolnar** [comment]
Might be time for some integration tests.

**Comment by aronmolnar** [comment]
Should be resolved.
Integration tests are on our agenda.
