### ISSUE TITLE
Newly created fields from Designs are not available for new templates

### ISSUE THREAD

**Issue by hacks2learn** [Syslifters/sysreptor#64]
Hello

Excellent tool BTW!  Is there a documented procedure on how to add new fields to findings and ultimately the report? I went thru the documentation and FAQs but cannot seem to find it.  The system works fine for using existing fields, however when I try to add a new one, I can never get it to appear as available in a new template even if I tell it to "Show fields of All Designs" ?

Thanks

**Comment by MWedl** [comment]
Hi

The list of available fields may be cached in your browser. Try to force reload the page and try again. 

Changing the template field filter only applies a display filter in the UI. The list of all available template fields is not reloaded from the API.

**Comment by hacks2learn** [comment]
Thanks @MWedl  Ctrl F5 on the browser did the trick... silly me, I should have tried that first.

**Comment by hacks2learn** [comment]
I also noticed that _new fields_ which are added will only be picked up by _new_ Projects.  Existing projects even if not in a _Finished_ state will `NOT` get the new fields.

**Comment by MWedl** [comment]
That's a feature not a bug :)

Projects do not directly use the global designs. Instead they create a snapshot of the design when it gets assigned to a project. This prevents unexpected changes of old projects when the design changes and also prevents data loss when a field is deleted from the design or the field data type is changed.

**Comment by hacks2learn** [comment]
Thanks!  That's what I figured...but thought I should comment in case someone else brings it up :)
