### ISSUE TITLE
Horizontal input overflow

### ISSUE THREAD

**Issue by noraj** [Syslifters/sysreptor#65]
## Issue

Horizontal input are overflowing the window if the text is too long.

https://github.com/Syslifters/sysreptor/assets/16578570/552950bf-1225-46d9-8c90-cd95175a79ab

## Solution

Add `cm-lineWrapping` class to the parent container.

![image](https://github.com/Syslifters/sysreptor/assets/16578570/644bbcfa-e5b2-4aaa-80d2-3ed5f18d4119)

## Environment

- Sysreptor version 0.110
- Firefox 116.0.1

**Comment by MWedl** [comment]
Thanks for reporting.

We have already mitigated input elements from overflowing pages (e.g. findings editor in projects). Unfortunately, on the template page there is a conflicting CSS rule that prevents the overflow prevention to kick in. We will fix this in the next release.

**Comment by MWedl** [comment]
Fixed in https://github.com/Syslifters/sysreptor/releases/tag/2023.114

**Comment by noraj** [comment]
I can confirm it's good now.
