### ISSUE TITLE
Spell checking with LanguageTool or default browser spell checking

### ISSUE THREAD

**Issue by noraj** [Syslifters/sysreptor#66]
I know your custom [**Spell Check**](https://docs.sysreptor.com/features-and-pricing/) is only included in the _Professional_ edition but (both for community and pro version) it would be nice to be able to switch to other solution as per user preferences:

- Default browser spell checking
- Plugin based spell checking

## Default browser spell checking

It would be as easy as modifying the attribute `spellcheck="false"` for each field and have an option `Enable default browser spell checking` in `/users/self/`.

## Plugin based spell checking

Software like [LanguageTool](https://languagetool.org/) or [Antidote](https://www.antidote.info/fr/antidote-web) are offering advanced spell checking with a plugin. They work by default with all text fields like textareas but sometime they don't work with some WYSIWYG editor ([example with EasyMDE](https://github.com/go-gitea/gitea/issues/18639) and [associated PR](https://github.com/go-gitea/gitea/pull/19776)).

In Sysreptor, It's working on the one line fields (e.g., precondition) but not on multi-line text fields (with a WYSIWYG editor, e.g., Impact) even when setting `contenteditable="true"` and `spellcheck="true"`.

**Comment by aronmolnar** [comment]
Thanks for this feedback.

We will implement a possibility for users to set `spellcheck` to true (`contenteditable` is already true).

It will probably be this button to enable/disable the spell check:

![image](https://github.com/Syslifters/sysreptor/assets/25219407/e7d42c58-75fb-4832-b2f8-18f7d8aaa666)

The setting will be stored in the browser's local storage and is applied to all fields.  
This should make it possible to - at least - use native browser spell checking.

However, there are drawbacks for native browser spell checks (such as limited or no multi language support).

If plugin based spell checks do not work, we'd rather regard this as  a bug in the plugins. The problem might be related to some markdown syntax-highlighting features we use.  
We will not troubleshoot this in detail, as we provide the official spell check in SysReptor Professional.

**Comment by MWedl** [comment]
Implemented in https://github.com/Syslifters/sysreptor/releases/tag/2023.119
