### ISSUE TITLE
Cannot edit template in other language

### ISSUE THREAD

**Issue by Moneysac90** [Syslifters/sysreptor#67]
In the latest version of sysreptor, support for multiple languages for templates has been added. However, it does not seem to be possible to edit the content of findings in other languages. This also happens in the default templates. 

As you can see in the following screenshot, it is not possible to modify the corresponding fields (e.g. Summary). 
![image](https://github.com/Syslifters/sysreptor/assets/20662108/32a88511-9bc3-4168-a3c2-8daba87ce2db)

**Comment by MWedl** [comment]
Hi,

in template translations you need to explicitly specify which fields you want to override in the current language by clicking the override button on the right.

![image](https://github.com/Syslifters/sysreptor/assets/29510012/3f2a8333-c1bd-499b-bbb0-53270ef034ba)

**Comment by Patralos** [comment]
We could try to unlock the field automatically on click (on the disabled field), but it might be hard for users to find a way to disable it again.

@MWedl

**Comment by aronmolnar** [comment]
Or maybe make the button more prominent?

![image](https://github.com/Syslifters/sysreptor/assets/25219407/6b15d74c-aced-44ec-9005-5c298feb8d78)

**Comment by MWedl** [comment]
> We could try to unlock the field automatically on click (on the disabled field), but it might be hard for users to find a way to disable it again.

We would have to find a new UI for disabling fields again. It will also be harder to see which fields are overridden and which are inherited from the main language.

Another suggestion: Maybe we could better highlight the button by settings a button background or increasing its size to span the whole height of fields. 

Before releasing multilanguage templates we tried to place the button on the left (because focus is more likely on the start of the field) but that looked crappy.

**Comment by richardschwabe** [comment]
An even simpler solution, might be to write a text at the top and put a look-alike button there. 
Another solution might be a pop-up for first-time users of translations, like a "tour". 
Or a hint when hovering over the field the user wants to edit. (Tooltip like this: https://vuetifyjs.com/en/components/tooltips/)

These are the most straightforward solutions from the top of my head, that I would explore.

**Comment by aronmolnar** [comment]
My personal suggestion is to go with option 2

**Comment by MWedl** [comment]
Implemented option 2 in https://github.com/Syslifters/sysreptor/releases/tag/2023.128
