### ISSUE TITLE
Language management

### ISSUE THREAD

**Issue by noraj** [Syslifters/sysreptor#7]
After importing demo data, I can see in finding template that I have two languages available:

![image](https://user-images.githubusercontent.com/16578570/236929644-5ccbc616-5a42-40be-914a-17ed8cb3be25.png)

However, I don't see any way to add or remove languages.

**Comment by aronmolnar** [comment]
We will fix this.

**Comment by noraj** [comment]
So how to set languages? `PREFERRED_LANGUAGES` as an env var in the docker-compose.yml ? Or only configurable through the django admin panel ?

**Comment by MWedl** [comment]
The best way is to add it as an environment variable to `deploy/app.env`. See https://docs.sysreptor.com/setup/configuration/
