### ISSUE TITLE
Mark a finding as fixed

### ISSUE THREAD

**Issue by NextGenBit** [Syslifters/sysreptor#73]
Hello,

It would be a good idea to implement a new feature regarding findings.

Mark a finding as "fixed" during retesting. If a finding is marked as fixed, it will be excluded by the graph containing the vulnerabilities. It shouldn't be considered a vulnerability any more but , we need it in the report.

**Comment by MWedl** [comment]
I agree that a checkbox is faster to tick when writing reports. The disadvantage is that a checkbox cannot differentiate between multiple states why/why not a finding is fixed. This is why we decided to provide the `retest_status` as an enum. 

It is possible to add a `is_fixed` boolean field in your design if a checkbox suites you use case better.  SysReptor currently does not use the value of `retest_status` internally (the value is just passed to the template for PDF rendering), so you don't miss any functionality.

**Comment by aronmolnar** [comment]
@NextGenBit Do you mean as a ui element in SysReptor?

**Comment by noraj** [comment]
> But maybe a checkbox like "Mark as fixed" would be more practical and faster.

It would be a duplicate with _Re-Test Status_ _Resolved_.

![image](https://github.com/Syslifters/sysreptor/assets/16578570/e8038f8c-ced1-4862-96a3-9b6349bde388)

I think it's better to have a re-test template including a graph filter so it's more flexible.

**Comment by aronmolnar** [comment]
Do you have any more inputs on your use case @NextGenBit?
