### ISSUE TITLE
Image Size Automation

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#85]
Any way to make the image size automatically fit the page height so it doesn't push it to the next page? Or if the image is too small it pushes it to the next page and tries to maximize the size?

**Comment by MWedl** [comment]
Unfortunately, I don't know any CSS rules that could achieve such a behavior.

You can, however, manually set image widths and heights in markdown (see https://docs.sysreptor.com/reporting/markdown-features/#html-attributes). After you finished writing reports you can review the PDF and adjust image widths/heights to polish the reports. 

```md
![image](img.png){width="50%"}
```

**Comment by vysecurity** [comment]
One problem I have is it takes around 2 minutes to generate once.

**Comment by MWedl** [comment]
That's a really long time. On our installations it usually takes only 2 to 10 seconds to render a PDF (dependening on the size and complexity of the document). How much RAM and CPUs are assigned to SysReptor. Maybe you can try assign more resources to speed up PDF rendering, since this is a very resource intensive operation.

**Comment by vysecurity** [comment]
So basically I have a VM with 8 GB ram and 8 CPU.

It's mostly my template is probably quite complex  hmmm

**Comment by MWedl** [comment]
SysReptor logs some basic timing information for PDF rendering. I suspect that weasyprint (HTML to PDF rendering library) is the slow part (log message `Function render_to_pdf took ...`). Maybe you can take a look at https://doc.courtbouillon.org/weasyprint/stable/common_use_cases.html#improve-rendering-speed-and-memory-use

**Comment by vysecurity** [comment]
How can I find the log file? Thanks!

**Comment by MWedl** [comment]
Logs are available in the docker logs of containers.
```sh
cd sysreptor/deploy
docker compose logs -f api
# Now render a PDF in the web UI to trigger the log messages
```

**Comment by aronmolnar** [comment]
You could also try to render it using our cloud infrastucture and see how the timing is there.

* Go to https://docs.sysreptor.com/
* Click "Playground"
* As soon as you are authenticated go to https://demo.sysre.pt/designs/private/
* Import your design as private design
* Create a test project and render

The data will automatically be cleaned up after two days.

**Comment by vysecurity** [comment]
![Warp-2023-08-29 at 11 25 31@2x](https://github.com/Syslifters/sysreptor/assets/3596242/1958c158-18ab-41a8-8b2c-0f704dfafd0f)

Are these figures normal?

**Comment by MWedl** [comment]
This is still very slow, but better than 2 minutes. It might result from long and complex projects.

What are the rendering times of our demo designs and projects (Demo design names: Margherita, Calzone, Matrix; if they are not present in your SysReptor instance you can download and import them from https://docs.sysreptor.com/assets/demo-projects.tar.gz and https://docs.sysreptor.com/assets/demo-designs.tar.gz). Are they slow too?

**Comment by vysecurity** [comment]
This is the result for Calzone:

```
2023-08-29 14:57:10,281 [INFO] root: Function render_to_html took 0:00:02.961884
2023-08-29 14:57:12,538 [INFO] root: Function render_to_pdf took 0:00:02.256246
2023-08-29 14:57:12,538 [INFO] root: Function encrypt_pdf took 0:00:00.000006
2023-08-29 14:57:12,541 [INFO] root: Function render_pdf_task took 0:00:05.221620
```
