### ISSUE TITLE
SysReptor Milestones: Request for Feedback

### ISSUE THREAD

**Issue by aronmolnar** [Syslifters/sysreptor#89]
We have recently defined next possible milestones for the SysReptor project.  
Up next are:
* Version history of findings, finding templates, designs (see https://github.com/Syslifters/sysreptor/discussions/81)
* Upgrade from Vue/Nuxt/Vuetify 2 to Vue/Nuxt/Vuetify 3
    * incl. UI/UX improvements
    * implementation of new Corporate Identity
* SysReptor CLI for automation

However, there is a lot more to make pentest reporting easier. Our future milestones and ideas are:

* LLM for template writing (https://github.com/Syslifters/sysreptor/discussions/83)
* Restrict user permissions to one project (https://github.com/Syslifters/sysreptor/discussions/82)
* Document sharing via SysReptor (https://github.com/Syslifters/sysreptor/discussions/80)
* Concurrent editing of findings (https://github.com/Syslifters/sysreptor/discussions/78)

We created a poll at https://github.com/Syslifters/sysreptor/discussions/88
Please vote :)

Do you have more ideas? Let us know here 👇

**Comment by vysecurity** [comment]
Wonder if there's any chance of a Word Doc output, or even CSV output for just Findings too.

**Comment by aronmolnar** [comment]
> Wonder if there's any chance [...] CSV output for just Findings too.

CSV export is rather difficult for a generic solution, because we use complex types in reports, like lists or objects that cannot easily be transformed to CSV.

However, I gave you access to our CLI tool, which is still in pre-alpha state (and a private project still). You can use this to export your reports to JSON, TOML or YAML.

You can git clone and...

```
pip3 install .
reptor conf
# Interactively add your API token, project details, etc.
reptor projects --export json  # or toml or yaml
```

**Comment by aronmolnar** [comment]
> Wonder if there's any chance of a Word Doc output [...]

docx is a difficult topic. We do not plan to officially support it (mostly due to closed specs, complexity, missing library support, etc.).

I played around with [pdf2docx](https://pypi.org/project/pdf2docx/) (which could also be integrated to the CLI tool) but the results are far from perfect.

There are issues with background colors. Also, headers and footers are not added as docx-headers/footers, so they are pushed to the next page, as soon as you write in the docx.


If you have other ideas how to convert or what might otherwise simplify your process for which you need the docx, let us know.

(Thanks for your constant feedbacks, BTW.)

**Comment by aronmolnar** [comment]
@vysecurity we tested a few more solutions for converting PDFs to docx.
We'd recommend Adobe Acrobat which delivers really good results.
