### ISSUE TITLE
Splitting Vulnerability Sections

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#90]
Currently I have sections such as:

```
Critical Risk Findings
Critical rIsk 1: ABCDEF

High Risk Findings
High risk 1: ABCDEF
```

However, I want to add 1 more layer such as:

```
Web app 1
Critical Risk Findings
Critical Risk 1: ABCDEF
High Risk Findings
High risk 1: dbgdsbd

Web app 2
Critical Risk Findings
Critical Risk 1: ABCDEF
High Risk Findings
High risk 1: dbgdsbd
```

Is there any way to tag individual findings within the findings list with an APPNAME or APPID, then use the HTML template to only print those findings for that web app, or to recurse through a list of APPNAME or APPID tags manually specified?

Let's say I have around 50 web applications, and I want to group it into its own individual section. Each finding for that web app will be tagged somehow with "webappname"?

**Comment by MWedl** [comment]
Hi,
you need to adapt your design to group findings. You can add a custom field of type enum or string (depending on your requirements) and group by that in HTML. In the last release we have added the functionality to customize finding sorting (configure in design -> finding fields). This affects the findings in the design and the frontend. If you order by APPID then by CVSS, the findings are grouped in the frontend too.

To group findings in the HTML template you can use something like that:
```html
<section v-for="findingGroup in lodash.groupBy(findings, f => f.appid)">
  <h1 class="in-toc numbered">Findings of {{ findingGroup[0].appid }}</h1>

  <div v-for="finding in findingGroup">
     <h2 class="in-toc numbered">{{ finding.title }}</h2>
     ...
  </div>
</section>
```

**Comment by vysecurity** [comment]
Thanks for the suggestion. I'll give it a shot.

**Comment by vysecurity** [comment]
Turns out it was never overcome. The `<template #risk>` tag seems to break `CommaAndJoin`...?

**Comment by MWedl** [comment]
The `<template #name>` syntax is used in Vue templates for so-called [slots](https://vuejs.org/guide/components/slots.html) to pass HTML data to `<comma-and-join>`. In the `<comma-and-join>` the slot-name (word after the `#`) can be anything, but it has to be unique. If you used `<template #risk>` multiple times, try to change it to unique names `<template #risk1>`, `<template #risk2>`, etc. 

If you want to iterate over a list and generate dynamic slots based on list contents, you can generate [dynamic slot names](https://vuejs.org/guide/components/slots.html#dynamic-slot-names) with `<template v-for="role in user.roles" #[role]>`. The generated dynamic slot names also have to be unique.
