### ISSUE TITLE
Finding Templates "Summary" Section

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#92]
Hi team,

Every time I create a finding, actually the "summary" is not used, but it still has a box and uses up a lot of space. Sometimes I accidentally write the finding in the summary instead of technical description, sometimes I write the recommendation into the technical description because there's the summary box that's supposed to be empty.

Is there any way for me to delete the summary from all findings?

**Comment by aronmolnar** [comment]
You can remove the summary finding field from your design.
In existing projects you need to go to the projects menu and re-chose your design (because projects hold a copy of your design to prevent unintended changes).

**Comment by vysecurity** [comment]
I'll give it a try shortly.
