### ISSUE TITLE
Chinese language support

### ISSUE THREAD

**Issue by chingru** [Syslifters/sysreptor#94]
How to make a generated PDF support Chinese?

**Comment by MWedl** [comment]
What do you mean exactly?
1. You are missing Chinese in the language selection?
2. PDF rendering breaks with Chinese texts?

For case 2. we are dependent on weasyprint (HTML to PDF library). This is out of our control.

**Comment by chingru** [comment]
The situation I'm currently facing is exactly like case 2. It appears that I need to look for alternative solutions. Thank you for your response.

**Comment by Patralos** [comment]
Hi @chingru,

we did some testing internally, and it doesn`t seem to be a problem with weasyprint, but just a missing font.

To use a new font you need to upload it to the asset tab of your design:

![image](https://github.com/Syslifters/sysreptor/assets/27063650/8a1ee77c-cc2e-4e8a-93c0-8a51ebd8e09d)

And reference the font in CSS like this:

```
@font-face {
    font-family: 'Noto Sans SC';
    src: url('NotoSansSC-Regular.woff2') format('woff2'),
        url('NotoSansSC-Regular.woff') format('woff'),
        url('NotoSansSC-Regular.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
    font-display: swap;
}

```

Please have a look if this works for you and provide some feedback :)

**Comment by MWedl** [comment]
We will add more Noto Sans fonts to the docker container in the next release, such that it supports Chinese and a range of other languages/character-sets.

**Comment by chingru** [comment]
Hi @Patralos 
I appreciate the methods you provided. Thanks to this, Chinese fonts are now displaying correctly, and I'm very thankful for your help.

![image](https://github.com/Syslifters/sysreptor/assets/8504537/0a63e8ee-1058-404a-8b31-a2c8be8bdf84)

**Comment by MWedl** [comment]
In the latest release (https://github.com/Syslifters/sysreptor/releases/tag/2023.122), we install Noto fonts for Chinese (and many other languages) by default. You no longer need to upload the fonts as asset in every design. Now, you just need:

```css
html {
  font-family: "Noto Sans";
}
```
