### ISSUE TITLE
Changing CVSS labelling "medium"

### ISSUE THREAD

**Issue by CUBE-DT** [Syslifters/sysreptor#95]
Is it possible to add a feature to rename the CVSS risk rating labels?

**Comment by MWedl** [comment]
Hi, you can translate/map the CVSS level labels via JavaScript expressions in the HTML template of your design. Following example shows how to translate them to German:

```html
<tr>
  <td>Risiko</td>
  <td :class="'risk-bg-' + finding.cvss.level">
    {{ ['Information', 'Gering', 'Mittel', 'Hoch', 'Kritisch'][finding.cvss.level_number - 1]}}
  </td>
</tr>
```

The risk labels in the SysReptor UI, however, cannot be changed and will still be in English.
