### ISSUE TITLE
Change Port

### ISSUE THREAD

**Issue by XejgaToast** [Syslifters/sysreptor#99]
Hello, I haven't found a way to change the port from 5000 to for example 80 or 8080 without installing a webserver. Is this possible in some kind of way?

**Comment by aronmolnar** [comment]
Yes, you can change the docker-compose.yml in the deploy folder:

`      - "127.0.0.1:5000:8000"`

https://github.com/Syslifters/sysreptor/blob/main/deploy/docker-compose.yml#L41
